/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables;


import com.jooq.jooqDemo.jooq.domain.tables.Indexes;
import com.jooq.jooqDemo.jooq.domain.tables.Keys;
import com.jooq.jooqDemo.jooq.domain.tables.Raadsmarine;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.NoticeRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Notice extends TableImpl<NoticeRecord> {

    private static final long serialVersionUID = -459474836;

    /**
     * The reference instance of <code>raadsmarine.NOTICE</code>
     */
    public static final Notice NOTICE = new Notice();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NoticeRecord> getRecordType() {
        return NoticeRecord.class;
    }

    /**
     * The column <code>raadsmarine.NOTICE.NOTICE_ID</code>.
     */
    public final TableField<NoticeRecord, Long> NOTICE_ID = createField("NOTICE_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>raadsmarine.NOTICE.CREATED_BY</code>.
     */
    public final TableField<NoticeRecord, String> CREATED_BY = createField("CREATED_BY", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.NOTICE.CREATED_DATE</code>.
     */
    public final TableField<NoticeRecord, Timestamp> CREATED_DATE = createField("CREATED_DATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>raadsmarine.NOTICE.NOTICE_BODY</code>.
     */
    public final TableField<NoticeRecord, String> NOTICE_BODY = createField("NOTICE_BODY", org.jooq.impl.SQLDataType.VARCHAR(10000), this, "");

    /**
     * The column <code>raadsmarine.NOTICE.NOTICE_DATE</code>.
     */
    public final TableField<NoticeRecord, Timestamp> NOTICE_DATE = createField("NOTICE_DATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>raadsmarine.NOTICE.NOTICE_DESCRIPTION</code>.
     */
    public final TableField<NoticeRecord, String> NOTICE_DESCRIPTION = createField("NOTICE_DESCRIPTION", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.NOTICE.NOTICE_HEADER</code>.
     */
    public final TableField<NoticeRecord, String> NOTICE_HEADER = createField("NOTICE_HEADER", org.jooq.impl.SQLDataType.VARCHAR(200), this, "");

    /**
     * The column <code>raadsmarine.NOTICE.UPDATED_BY</code>.
     */
    public final TableField<NoticeRecord, String> UPDATED_BY = createField("UPDATED_BY", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.NOTICE.UPDATED_DATE</code>.
     */
    public final TableField<NoticeRecord, Timestamp> UPDATED_DATE = createField("UPDATED_DATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>raadsmarine.NOTICE</code> table reference
     */
    public Notice() {
        this(DSL.name("NOTICE"), null);
    }

    /**
     * Create an aliased <code>raadsmarine.NOTICE</code> table reference
     */
    public Notice(String alias) {
        this(DSL.name(alias), NOTICE);
    }

    /**
     * Create an aliased <code>raadsmarine.NOTICE</code> table reference
     */
    public Notice(Name alias) {
        this(alias, NOTICE);
    }

    private Notice(Name alias, Table<NoticeRecord> aliased) {
        this(alias, aliased, null);
    }

    private Notice(Name alias, Table<NoticeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Raadsmarine.RAADSMARINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.NOTICE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<NoticeRecord, Long> getIdentity() {
        return Keys.IDENTITY_NOTICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<NoticeRecord> getPrimaryKey() {
        return Keys.KEY_NOTICE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<NoticeRecord>> getKeys() {
        return Arrays.<UniqueKey<NoticeRecord>>asList(Keys.KEY_NOTICE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Notice as(String alias) {
        return new Notice(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Notice as(Name alias) {
        return new Notice(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Notice rename(String name) {
        return new Notice(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Notice rename(Name name) {
        return new Notice(name, null);
    }
}
