/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables;


import com.jooq.jooqDemo.jooq.domain.tables.Indexes;
import com.jooq.jooqDemo.jooq.domain.tables.Keys;
import com.jooq.jooqDemo.jooq.domain.tables.Raadsmarine;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.OauthRefreshTokenRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OauthRefreshToken extends TableImpl<OauthRefreshTokenRecord> {

    private static final long serialVersionUID = -815518049;

    /**
     * The reference instance of <code>raadsmarine.oauth_refresh_token</code>
     */
    public static final OauthRefreshToken OAUTH_REFRESH_TOKEN = new OauthRefreshToken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OauthRefreshTokenRecord> getRecordType() {
        return OauthRefreshTokenRecord.class;
    }

    /**
     * The column <code>raadsmarine.oauth_refresh_token.token_id</code>.
     */
    public final TableField<OauthRefreshTokenRecord, String> TOKEN_ID = createField("token_id", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>raadsmarine.oauth_refresh_token.authentication</code>.
     */
    public final TableField<OauthRefreshTokenRecord, byte[]> AUTHENTICATION = createField("authentication", org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * The column <code>raadsmarine.oauth_refresh_token.token</code>.
     */
    public final TableField<OauthRefreshTokenRecord, byte[]> TOKEN = createField("token", org.jooq.impl.SQLDataType.BLOB, this, "");

    /**
     * Create a <code>raadsmarine.oauth_refresh_token</code> table reference
     */
    public OauthRefreshToken() {
        this(DSL.name("oauth_refresh_token"), null);
    }

    /**
     * Create an aliased <code>raadsmarine.oauth_refresh_token</code> table reference
     */
    public OauthRefreshToken(String alias) {
        this(DSL.name(alias), OAUTH_REFRESH_TOKEN);
    }

    /**
     * Create an aliased <code>raadsmarine.oauth_refresh_token</code> table reference
     */
    public OauthRefreshToken(Name alias) {
        this(alias, OAUTH_REFRESH_TOKEN);
    }

    private OauthRefreshToken(Name alias, Table<OauthRefreshTokenRecord> aliased) {
        this(alias, aliased, null);
    }

    private OauthRefreshToken(Name alias, Table<OauthRefreshTokenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Raadsmarine.RAADSMARINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.OAUTH_REFRESH_TOKEN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OauthRefreshTokenRecord> getPrimaryKey() {
        return Keys.KEY_OAUTH_REFRESH_TOKEN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OauthRefreshTokenRecord>> getKeys() {
        return Arrays.<UniqueKey<OauthRefreshTokenRecord>>asList(Keys.KEY_OAUTH_REFRESH_TOKEN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthRefreshToken as(String alias) {
        return new OauthRefreshToken(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthRefreshToken as(Name alias) {
        return new OauthRefreshToken(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OauthRefreshToken rename(String name) {
        return new OauthRefreshToken(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OauthRefreshToken rename(Name name) {
        return new OauthRefreshToken(name, null);
    }
}
