/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables;


import com.jooq.jooqDemo.jooq.domain.tables.Indexes;
import com.jooq.jooqDemo.jooq.domain.tables.Keys;
import com.jooq.jooqDemo.jooq.domain.tables.Raadsmarine;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.ProductRecord;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Product extends TableImpl<ProductRecord> {

    private static final long serialVersionUID = -1019006746;

    /**
     * The reference instance of <code>raadsmarine.Product</code>
     */
    public static final Product PRODUCT = new Product();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductRecord> getRecordType() {
        return ProductRecord.class;
    }

    /**
     * The column <code>raadsmarine.Product.PRODUCT_ID</code>.
     */
    public final TableField<ProductRecord, Long> PRODUCT_ID = createField("PRODUCT_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>raadsmarine.Product.PRODUCT_NAME</code>.
     */
    public final TableField<ProductRecord, String> PRODUCT_NAME = createField("PRODUCT_NAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.Product.PRODUCT_PRICE</code>.
     */
    public final TableField<ProductRecord, BigDecimal> PRODUCT_PRICE = createField("PRODUCT_PRICE", org.jooq.impl.SQLDataType.DECIMAL(19, 2), this, "");

    /**
     * The column <code>raadsmarine.Product.category_CATEGORY_ID</code>.
     */
    public final TableField<ProductRecord, Long> CATEGORY_CATEGORY_ID = createField("category_CATEGORY_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>raadsmarine.Product.manufacturer_MANUFACTURER_ID</code>.
     */
    public final TableField<ProductRecord, Long> MANUFACTURER_MANUFACTURER_ID = createField("manufacturer_MANUFACTURER_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>raadsmarine.Product.productDetail_DETAIL_ID</code>.
     */
    public final TableField<ProductRecord, Long> PRODUCTDETAIL_DETAIL_ID = createField("productDetail_DETAIL_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>raadsmarine.Product</code> table reference
     */
    public Product() {
        this(DSL.name("Product"), null);
    }

    /**
     * Create an aliased <code>raadsmarine.Product</code> table reference
     */
    public Product(String alias) {
        this(DSL.name(alias), PRODUCT);
    }

    /**
     * Create an aliased <code>raadsmarine.Product</code> table reference
     */
    public Product(Name alias) {
        this(alias, PRODUCT);
    }

    private Product(Name alias, Table<ProductRecord> aliased) {
        this(alias, aliased, null);
    }

    private Product(Name alias, Table<ProductRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Raadsmarine.RAADSMARINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRODUCT_FK_7YSG84NNNEBFW1AYUSFMGQQX1, Indexes.PRODUCT_FK_F40ERND8GK8N3N817A1Y0LHMU, Indexes.PRODUCT_FK_PQBNOVWSSGSWCML7QJAMM4PT7, Indexes.PRODUCT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ProductRecord, Long> getIdentity() {
        return Keys.IDENTITY_PRODUCT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProductRecord> getPrimaryKey() {
        return Keys.KEY_PRODUCT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProductRecord>> getKeys() {
        return Arrays.<UniqueKey<ProductRecord>>asList(Keys.KEY_PRODUCT_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ProductRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProductRecord, ?>>asList(Keys.FK_PQBNOVWSSGSWCML7QJAMM4PT7, Keys.FK_F40ERND8GK8N3N817A1Y0LHMU, Keys.FK_7YSG84NNNEBFW1AYUSFMGQQX1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Product as(String alias) {
        return new Product(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Product as(Name alias) {
        return new Product(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Product rename(String name) {
        return new Product(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Product rename(Name name) {
        return new Product(name, null);
    }
}
