/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables;


import com.jooq.jooqDemo.jooq.domain.tables.Indexes;
import com.jooq.jooqDemo.jooq.domain.tables.Keys;
import com.jooq.jooqDemo.jooq.domain.tables.Raadsmarine;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.ProductDetailsRecord;

import java.sql.Time;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductDetails extends TableImpl<ProductDetailsRecord> {

    private static final long serialVersionUID = -1104402252;

    /**
     * The reference instance of <code>raadsmarine.PRODUCT_DETAILS</code>
     */
    public static final ProductDetails PRODUCT_DETAILS = new ProductDetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProductDetailsRecord> getRecordType() {
        return ProductDetailsRecord.class;
    }

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.DETAIL_ID</code>.
     */
    public final TableField<ProductDetailsRecord, Long> DETAIL_ID = createField("DETAIL_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.BATTERY_SPAN</code>.
     */
    public final TableField<ProductDetailsRecord, String> BATTERY_SPAN = createField("BATTERY_SPAN", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.BATTERY_TYPE</code>.
     */
    public final TableField<ProductDetailsRecord, String> BATTERY_TYPE = createField("BATTERY_TYPE", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.CAPACITY</code>.
     */
    public final TableField<ProductDetailsRecord, Integer> CAPACITY = createField("CAPACITY", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.CHARGER_SPECS</code>.
     */
    public final TableField<ProductDetailsRecord, String> CHARGER_SPECS = createField("CHARGER_SPECS", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.CHARGING_TIME</code>.
     */
    public final TableField<ProductDetailsRecord, Time> CHARGING_TIME = createField("CHARGING_TIME", org.jooq.impl.SQLDataType.TIME, this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.CONSTRUCTION</code>.
     */
    public final TableField<ProductDetailsRecord, Double> CONSTRUCTION = createField("CONSTRUCTION", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.CONTROL_SYSTEM</code>.
     */
    public final TableField<ProductDetailsRecord, String> CONTROL_SYSTEM = createField("CONTROL_SYSTEM", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.DIVING_DEPTH</code>.
     */
    public final TableField<ProductDetailsRecord, Double> DIVING_DEPTH = createField("DIVING_DEPTH", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.DRAUGHT</code>.
     */
    public final TableField<ProductDetailsRecord, String> DRAUGHT = createField("DRAUGHT", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.ENGINE_TYPE</code>.
     */
    public final TableField<ProductDetailsRecord, String> ENGINE_TYPE = createField("ENGINE_TYPE", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.FUEL_TANK_CAPACITY</code>.
     */
    public final TableField<ProductDetailsRecord, Double> FUEL_TANK_CAPACITY = createField("FUEL_TANK_CAPACITY", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.GIRTH</code>.
     */
    public final TableField<ProductDetailsRecord, Double> GIRTH = createField("GIRTH", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.HEIGHT</code>.
     */
    public final TableField<ProductDetailsRecord, Double> HEIGHT = createField("HEIGHT", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.HULL_LENGTH</code>.
     */
    public final TableField<ProductDetailsRecord, Double> HULL_LENGTH = createField("HULL_LENGTH", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.LENGTH</code>.
     */
    public final TableField<ProductDetailsRecord, Double> LENGTH = createField("LENGTH", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.MAKE</code>.
     */
    public final TableField<ProductDetailsRecord, String> MAKE = createField("MAKE", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.MAX_SPEED</code>.
     */
    public final TableField<ProductDetailsRecord, Double> MAX_SPEED = createField("MAX_SPEED", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.MODEL</code>.
     */
    public final TableField<ProductDetailsRecord, String> MODEL = createField("MODEL", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.MOTOR_POWER</code>.
     */
    public final TableField<ProductDetailsRecord, Long> MOTOR_POWER = createField("MOTOR_POWER", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.OPERATING_TIME</code>.
     */
    public final TableField<ProductDetailsRecord, Time> OPERATING_TIME = createField("OPERATING_TIME", org.jooq.impl.SQLDataType.TIME, this, "");

    /**
     * The column <code>raadsmarine.PRODUCT_DETAILS.WEIGHT</code>.
     */
    public final TableField<ProductDetailsRecord, Double> WEIGHT = createField("WEIGHT", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>raadsmarine.PRODUCT_DETAILS</code> table reference
     */
    public ProductDetails() {
        this(DSL.name("PRODUCT_DETAILS"), null);
    }

    /**
     * Create an aliased <code>raadsmarine.PRODUCT_DETAILS</code> table reference
     */
    public ProductDetails(String alias) {
        this(DSL.name(alias), PRODUCT_DETAILS);
    }

    /**
     * Create an aliased <code>raadsmarine.PRODUCT_DETAILS</code> table reference
     */
    public ProductDetails(Name alias) {
        this(alias, PRODUCT_DETAILS);
    }

    private ProductDetails(Name alias, Table<ProductDetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProductDetails(Name alias, Table<ProductDetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Raadsmarine.RAADSMARINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PRODUCT_DETAILS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ProductDetailsRecord, Long> getIdentity() {
        return Keys.IDENTITY_PRODUCT_DETAILS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProductDetailsRecord> getPrimaryKey() {
        return Keys.KEY_PRODUCT_DETAILS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProductDetailsRecord>> getKeys() {
        return Arrays.<UniqueKey<ProductDetailsRecord>>asList(Keys.KEY_PRODUCT_DETAILS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductDetails as(String alias) {
        return new ProductDetails(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductDetails as(Name alias) {
        return new ProductDetails(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductDetails rename(String name) {
        return new ProductDetails(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ProductDetails rename(Name name) {
        return new ProductDetails(name, null);
    }
}
