/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables;


import com.jooq.jooqDemo.jooq.domain.tables.Indexes;
import com.jooq.jooqDemo.jooq.domain.tables.Keys;
import com.jooq.jooqDemo.jooq.domain.tables.Raadsmarine;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.RoleModuleRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleModule extends TableImpl<RoleModuleRecord> {

    private static final long serialVersionUID = -451007180;

    /**
     * The reference instance of <code>raadsmarine.ROLE_MODULE</code>
     */
    public static final RoleModule ROLE_MODULE = new RoleModule();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RoleModuleRecord> getRecordType() {
        return RoleModuleRecord.class;
    }

    /**
     * The column <code>raadsmarine.ROLE_MODULE.ROLE_MODULE_ID</code>.
     */
    public final TableField<RoleModuleRecord, String> ROLE_MODULE_ID = createField("ROLE_MODULE_ID", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>raadsmarine.ROLE_MODULE.CREATED_BY</code>.
     */
    public final TableField<RoleModuleRecord, String> CREATED_BY = createField("CREATED_BY", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.ROLE_MODULE.CREATED_DATE</code>.
     */
    public final TableField<RoleModuleRecord, Timestamp> CREATED_DATE = createField("CREATED_DATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>raadsmarine.ROLE_MODULE.CAN_DELETE</code>.
     */
    public final TableField<RoleModuleRecord, Boolean> CAN_DELETE = createField("CAN_DELETE", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>raadsmarine.ROLE_MODULE.CAN_UPDATE</code>.
     */
    public final TableField<RoleModuleRecord, Boolean> CAN_UPDATE = createField("CAN_UPDATE", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>raadsmarine.ROLE_MODULE.UPDATED_BY</code>.
     */
    public final TableField<RoleModuleRecord, String> UPDATED_BY = createField("UPDATED_BY", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.ROLE_MODULE.UPDATED_DATE</code>.
     */
    public final TableField<RoleModuleRecord, Timestamp> UPDATED_DATE = createField("UPDATED_DATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>raadsmarine.ROLE_MODULE.CAN_VIEW</code>.
     */
    public final TableField<RoleModuleRecord, Boolean> CAN_VIEW = createField("CAN_VIEW", org.jooq.impl.SQLDataType.BIT, this, "");

    /**
     * The column <code>raadsmarine.ROLE_MODULE.MODULE_ID</code>.
     */
    public final TableField<RoleModuleRecord, String> MODULE_ID = createField("MODULE_ID", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.ROLE_MODULE.ROLE_ID</code>.
     */
    public final TableField<RoleModuleRecord, Long> ROLE_ID = createField("ROLE_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>raadsmarine.ROLE_MODULE</code> table reference
     */
    public RoleModule() {
        this(DSL.name("ROLE_MODULE"), null);
    }

    /**
     * Create an aliased <code>raadsmarine.ROLE_MODULE</code> table reference
     */
    public RoleModule(String alias) {
        this(DSL.name(alias), ROLE_MODULE);
    }

    /**
     * Create an aliased <code>raadsmarine.ROLE_MODULE</code> table reference
     */
    public RoleModule(Name alias) {
        this(alias, ROLE_MODULE);
    }

    private RoleModule(Name alias, Table<RoleModuleRecord> aliased) {
        this(alias, aliased, null);
    }

    private RoleModule(Name alias, Table<RoleModuleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Raadsmarine.RAADSMARINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ROLE_MODULE_FK_J12G0HSA3FDOWTKCFDOO4NV1X, Indexes.ROLE_MODULE_FK_JHE6FQV41HLFNX6A9WFOB641L, Indexes.ROLE_MODULE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RoleModuleRecord> getPrimaryKey() {
        return Keys.KEY_ROLE_MODULE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RoleModuleRecord>> getKeys() {
        return Arrays.<UniqueKey<RoleModuleRecord>>asList(Keys.KEY_ROLE_MODULE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RoleModuleRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RoleModuleRecord, ?>>asList(Keys.FK_J12G0HSA3FDOWTKCFDOO4NV1X, Keys.FK_JHE6FQV41HLFNX6A9WFOB641L);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleModule as(String alias) {
        return new RoleModule(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleModule as(Name alias) {
        return new RoleModule(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleModule rename(String name) {
        return new RoleModule(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RoleModule rename(Name name) {
        return new RoleModule(name, null);
    }
}
