/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables;


import com.jooq.jooqDemo.jooq.domain.tables.Indexes;
import com.jooq.jooqDemo.jooq.domain.tables.Keys;
import com.jooq.jooqDemo.jooq.domain.tables.Raadsmarine;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.StudentRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Student extends TableImpl<StudentRecord> {

    private static final long serialVersionUID = 1245726832;

    /**
     * The reference instance of <code>raadsmarine.STUDENT</code>
     */
    public static final Student STUDENT = new Student();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StudentRecord> getRecordType() {
        return StudentRecord.class;
    }

    /**
     * The column <code>raadsmarine.STUDENT.PERSON_ID</code>.
     */
    public final TableField<StudentRecord, Long> PERSON_ID = createField("PERSON_ID", org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>raadsmarine.STUDENT.ADDRESS</code>.
     */
    public final TableField<StudentRecord, String> ADDRESS = createField("ADDRESS", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.STUDENT.AREA</code>.
     */
    public final TableField<StudentRecord, Long> AREA = createField("AREA", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>raadsmarine.STUDENT.CITY</code>.
     */
    public final TableField<StudentRecord, Integer> CITY = createField("CITY", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>raadsmarine.STUDENT.COUNTRY</code>.
     */
    public final TableField<StudentRecord, String> COUNTRY = createField("COUNTRY", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.STUDENT.CREATED_BY</code>.
     */
    public final TableField<StudentRecord, String> CREATED_BY = createField("CREATED_BY", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.STUDENT.CREATED_DATE</code>.
     */
    public final TableField<StudentRecord, Timestamp> CREATED_DATE = createField("CREATED_DATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>raadsmarine.STUDENT.DISTRICT</code>.
     */
    public final TableField<StudentRecord, Long> DISTRICT = createField("DISTRICT", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>raadsmarine.STUDENT.MOBILE_NUMBER</code>.
     */
    public final TableField<StudentRecord, String> MOBILE_NUMBER = createField("MOBILE_NUMBER", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.STUDENT.PIN</code>.
     */
    public final TableField<StudentRecord, Integer> PIN = createField("PIN", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>raadsmarine.STUDENT.STATE</code>.
     */
    public final TableField<StudentRecord, Integer> STATE = createField("STATE", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>raadsmarine.STUDENT.STUDENT_FIRST_NAME</code>.
     */
    public final TableField<StudentRecord, String> STUDENT_FIRST_NAME = createField("STUDENT_FIRST_NAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.STUDENT.STUDENT_LAST_NAME</code>.
     */
    public final TableField<StudentRecord, String> STUDENT_LAST_NAME = createField("STUDENT_LAST_NAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.STUDENT.STUDENT_MIDDLE_NAME</code>.
     */
    public final TableField<StudentRecord, String> STUDENT_MIDDLE_NAME = createField("STUDENT_MIDDLE_NAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.STUDENT.STUDENT_PARENT_FIRST_NAME</code>.
     */
    public final TableField<StudentRecord, String> STUDENT_PARENT_FIRST_NAME = createField("STUDENT_PARENT_FIRST_NAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.STUDENT.STUDENT_PARENT_LAST_NAME</code>.
     */
    public final TableField<StudentRecord, String> STUDENT_PARENT_LAST_NAME = createField("STUDENT_PARENT_LAST_NAME", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.STUDENT.SUB_AREA</code>.
     */
    public final TableField<StudentRecord, Long> SUB_AREA = createField("SUB_AREA", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>raadsmarine.STUDENT.UPDATED_BY</code>.
     */
    public final TableField<StudentRecord, String> UPDATED_BY = createField("UPDATED_BY", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>raadsmarine.STUDENT.UPDATED_DATE</code>.
     */
    public final TableField<StudentRecord, Timestamp> UPDATED_DATE = createField("UPDATED_DATE", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>raadsmarine.STUDENT.standard_STANDARD_ID</code>.
     */
    public final TableField<StudentRecord, Long> STANDARD_STANDARD_ID = createField("standard_STANDARD_ID", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>raadsmarine.STUDENT.user_UserId</code>.
     */
    public final TableField<StudentRecord, Long> USER_USERID = createField("user_UserId", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>raadsmarine.STUDENT</code> table reference
     */
    public Student() {
        this(DSL.name("STUDENT"), null);
    }

    /**
     * Create an aliased <code>raadsmarine.STUDENT</code> table reference
     */
    public Student(String alias) {
        this(DSL.name(alias), STUDENT);
    }

    /**
     * Create an aliased <code>raadsmarine.STUDENT</code> table reference
     */
    public Student(Name alias) {
        this(alias, STUDENT);
    }

    private Student(Name alias, Table<StudentRecord> aliased) {
        this(alias, aliased, null);
    }

    private Student(Name alias, Table<StudentRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Raadsmarine.RAADSMARINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.STUDENT_FK_FA4G3ACW4R880IA81CCUHNLDQ, Indexes.STUDENT_FK_RCN7L23KVL83VQV59HSRMELR1, Indexes.STUDENT_PRIMARY, Indexes.STUDENT_UK_7W7FCHFB0GMTCFXCKR2UI6FLM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<StudentRecord, Long> getIdentity() {
        return Keys.IDENTITY_STUDENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<StudentRecord> getPrimaryKey() {
        return Keys.KEY_STUDENT_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<StudentRecord>> getKeys() {
        return Arrays.<UniqueKey<StudentRecord>>asList(Keys.KEY_STUDENT_PRIMARY, Keys.KEY_STUDENT_UK_7W7FCHFB0GMTCFXCKR2UI6FLM);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<StudentRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<StudentRecord, ?>>asList(Keys.FK_FA4G3ACW4R880IA81CCUHNLDQ, Keys.FK_RCN7L23KVL83VQV59HSRMELR1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Student as(String alias) {
        return new Student(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Student as(Name alias) {
        return new Student(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Student rename(String name) {
        return new Student(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Student rename(Name name) {
        return new Student(name, null);
    }
}
