/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables.records;


import com.jooq.jooqDemo.jooq.domain.tables.tables.Audit;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditRecord extends UpdatableRecordImpl<AuditRecord> implements Record7<Long, String, Timestamp, BigDecimal, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -325206574;

    /**
     * Setter for <code>raadsmarine.Audit.AUDIT_ID</code>.
     */
    public void setAuditId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>raadsmarine.Audit.AUDIT_ID</code>.
     */
    public Long getAuditId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raadsmarine.Audit.CREATED_BY</code>.
     */
    public void setCreatedBy(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raadsmarine.Audit.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raadsmarine.Audit.CREATED_DATE</code>.
     */
    public void setCreatedDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>raadsmarine.Audit.CREATED_DATE</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>raadsmarine.Audit.NO_OF_HITS</code>.
     */
    public void setNoOfHits(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>raadsmarine.Audit.NO_OF_HITS</code>.
     */
    public BigDecimal getNoOfHits() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>raadsmarine.Audit.UPDATED_BY</code>.
     */
    public void setUpdatedBy(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>raadsmarine.Audit.UPDATED_BY</code>.
     */
    public String getUpdatedBy() {
        return (String) get(4);
    }

    /**
     * Setter for <code>raadsmarine.Audit.UPDATED_DATE</code>.
     */
    public void setUpdatedDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>raadsmarine.Audit.UPDATED_DATE</code>.
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>raadsmarine.Audit.VISIT_DATE</code>.
     */
    public void setVisitDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>raadsmarine.Audit.VISIT_DATE</code>.
     */
    public Timestamp getVisitDate() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, Timestamp, BigDecimal, String, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, Timestamp, BigDecimal, String, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Audit.AUDIT.AUDIT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Audit.AUDIT.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Audit.AUDIT.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return Audit.AUDIT.NO_OF_HITS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Audit.AUDIT.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Audit.AUDIT.UPDATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Audit.AUDIT.VISIT_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getAuditId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getNoOfHits();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getVisitDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getAuditId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getNoOfHits();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getVisitDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditRecord value1(Long value) {
        setAuditId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditRecord value2(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditRecord value3(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditRecord value4(BigDecimal value) {
        setNoOfHits(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditRecord value5(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditRecord value6(Timestamp value) {
        setUpdatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditRecord value7(Timestamp value) {
        setVisitDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuditRecord values(Long value1, String value2, Timestamp value3, BigDecimal value4, String value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuditRecord
     */
    public AuditRecord() {
        super(Audit.AUDIT);
    }

    /**
     * Create a detached, initialised AuditRecord
     */
    public AuditRecord(Long auditId, String createdBy, Timestamp createdDate, BigDecimal noOfHits, String updatedBy, Timestamp updatedDate, Timestamp visitDate) {
        super(Audit.AUDIT);

        set(0, auditId);
        set(1, createdBy);
        set(2, createdDate);
        set(3, noOfHits);
        set(4, updatedBy);
        set(5, updatedDate);
        set(6, visitDate);
    }
}
