/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables.records;


import com.jooq.jooqDemo.jooq.domain.tables.tables.Feedback;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FeedbackRecord extends UpdatableRecordImpl<FeedbackRecord> implements Record9<Long, String, String, String, String, String, Double, String, Long> {

    private static final long serialVersionUID = 683947759;

    /**
     * Setter for <code>raadsmarine.Feedback.FEEDBACK_ID</code>.
     */
    public void setFeedbackId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>raadsmarine.Feedback.FEEDBACK_ID</code>.
     */
    public Long getFeedbackId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raadsmarine.Feedback.ADDRESS</code>.
     */
    public void setAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raadsmarine.Feedback.ADDRESS</code>.
     */
    public String getAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raadsmarine.Feedback.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>raadsmarine.Feedback.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>raadsmarine.Feedback.FEEDBACK_LINE1</code>.
     */
    public void setFeedbackLine1(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>raadsmarine.Feedback.FEEDBACK_LINE1</code>.
     */
    public String getFeedbackLine1() {
        return (String) get(3);
    }

    /**
     * Setter for <code>raadsmarine.Feedback.FEEDBACK_LINE2</code>.
     */
    public void setFeedbackLine2(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>raadsmarine.Feedback.FEEDBACK_LINE2</code>.
     */
    public String getFeedbackLine2() {
        return (String) get(4);
    }

    /**
     * Setter for <code>raadsmarine.Feedback.PHONE</code>.
     */
    public void setPhone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>raadsmarine.Feedback.PHONE</code>.
     */
    public String getPhone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>raadsmarine.Feedback.RATING</code>.
     */
    public void setRating(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>raadsmarine.Feedback.RATING</code>.
     */
    public Double getRating() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>raadsmarine.Feedback.USER_NAME</code>.
     */
    public void setUserName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>raadsmarine.Feedback.USER_NAME</code>.
     */
    public String getUserName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>raadsmarine.Feedback.product_PRODUCT_ID</code>.
     */
    public void setProductProductId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>raadsmarine.Feedback.product_PRODUCT_ID</code>.
     */
    public Long getProductProductId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, String, Double, String, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, String, String, String, String, Double, String, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Feedback.FEEDBACK.FEEDBACK_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Feedback.FEEDBACK.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Feedback.FEEDBACK.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Feedback.FEEDBACK.FEEDBACK_LINE1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Feedback.FEEDBACK.FEEDBACK_LINE2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Feedback.FEEDBACK.PHONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return Feedback.FEEDBACK.RATING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Feedback.FEEDBACK.USER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field9() {
        return Feedback.FEEDBACK.PRODUCT_PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getFeedbackId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFeedbackLine1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getFeedbackLine2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component9() {
        return getProductProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getFeedbackId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFeedbackLine1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFeedbackLine2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPhone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getRating();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUserName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value9() {
        return getProductProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value1(Long value) {
        setFeedbackId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value2(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value3(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value4(String value) {
        setFeedbackLine1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value5(String value) {
        setFeedbackLine2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value6(String value) {
        setPhone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value7(Double value) {
        setRating(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value8(String value) {
        setUserName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord value9(Long value) {
        setProductProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FeedbackRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Double value7, String value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FeedbackRecord
     */
    public FeedbackRecord() {
        super(Feedback.FEEDBACK);
    }

    /**
     * Create a detached, initialised FeedbackRecord
     */
    public FeedbackRecord(Long feedbackId, String address, String email, String feedbackLine1, String feedbackLine2, String phone, Double rating, String userName, Long productProductId) {
        super(Feedback.FEEDBACK);

        set(0, feedbackId);
        set(1, address);
        set(2, email);
        set(3, feedbackLine1);
        set(4, feedbackLine2);
        set(5, phone);
        set(6, rating);
        set(7, userName);
        set(8, productProductId);
    }
}
