/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables.records;


import com.jooq.jooqDemo.jooq.domain.tables.tables.Image;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ImageRecord extends UpdatableRecordImpl<ImageRecord> implements Record7<Long, String, String, String, String, String, Long> {

    private static final long serialVersionUID = -13621905;

    /**
     * Setter for <code>raadsmarine.Image.IMAGE_ID</code>.
     */
    public void setImageId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>raadsmarine.Image.IMAGE_ID</code>.
     */
    public Long getImageId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raadsmarine.Image.IMAGE_DESCRIPTION</code>.
     */
    public void setImageDescription(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raadsmarine.Image.IMAGE_DESCRIPTION</code>.
     */
    public String getImageDescription() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raadsmarine.Image.IMAGE_URL_HD</code>.
     */
    public void setImageUrlHd(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>raadsmarine.Image.IMAGE_URL_HD</code>.
     */
    public String getImageUrlHd() {
        return (String) get(2);
    }

    /**
     * Setter for <code>raadsmarine.Image.IMAGE_URL_LARGE</code>.
     */
    public void setImageUrlLarge(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>raadsmarine.Image.IMAGE_URL_LARGE</code>.
     */
    public String getImageUrlLarge() {
        return (String) get(3);
    }

    /**
     * Setter for <code>raadsmarine.Image.IMAGE_URL_MEDIUM</code>.
     */
    public void setImageUrlMedium(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>raadsmarine.Image.IMAGE_URL_MEDIUM</code>.
     */
    public String getImageUrlMedium() {
        return (String) get(4);
    }

    /**
     * Setter for <code>raadsmarine.Image.IMAGE_URL_SMALL</code>.
     */
    public void setImageUrlSmall(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>raadsmarine.Image.IMAGE_URL_SMALL</code>.
     */
    public String getImageUrlSmall() {
        return (String) get(5);
    }

    /**
     * Setter for <code>raadsmarine.Image.product_PRODUCT_ID</code>.
     */
    public void setProductProductId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>raadsmarine.Image.product_PRODUCT_ID</code>.
     */
    public Long getProductProductId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, String, String, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, String, String, String, String, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Image.IMAGE.IMAGE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Image.IMAGE.IMAGE_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Image.IMAGE.IMAGE_URL_HD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Image.IMAGE.IMAGE_URL_LARGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Image.IMAGE.IMAGE_URL_MEDIUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Image.IMAGE.IMAGE_URL_SMALL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Image.IMAGE.PRODUCT_PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getImageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getImageDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getImageUrlHd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getImageUrlLarge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getImageUrlMedium();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getImageUrlSmall();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getProductProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getImageId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getImageDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getImageUrlHd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getImageUrlLarge();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getImageUrlMedium();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getImageUrlSmall();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getProductProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ImageRecord value1(Long value) {
        setImageId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ImageRecord value2(String value) {
        setImageDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ImageRecord value3(String value) {
        setImageUrlHd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ImageRecord value4(String value) {
        setImageUrlLarge(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ImageRecord value5(String value) {
        setImageUrlMedium(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ImageRecord value6(String value) {
        setImageUrlSmall(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ImageRecord value7(Long value) {
        setProductProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ImageRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ImageRecord
     */
    public ImageRecord() {
        super(Image.IMAGE);
    }

    /**
     * Create a detached, initialised ImageRecord
     */
    public ImageRecord(Long imageId, String imageDescription, String imageUrlHd, String imageUrlLarge, String imageUrlMedium, String imageUrlSmall, Long productProductId) {
        super(Image.IMAGE);

        set(0, imageId);
        set(1, imageDescription);
        set(2, imageUrlHd);
        set(3, imageUrlLarge);
        set(4, imageUrlMedium);
        set(5, imageUrlSmall);
        set(6, productProductId);
    }
}
