/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables.records;


import com.jooq.jooqDemo.jooq.domain.tables.tables.Manufacturer;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ManufacturerRecord extends UpdatableRecordImpl<ManufacturerRecord> implements Record4<Long, String, String, String> {

    private static final long serialVersionUID = 923539577;

    /**
     * Setter for <code>raadsmarine.Manufacturer.MANUFACTURER_ID</code>.
     */
    public void setManufacturerId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>raadsmarine.Manufacturer.MANUFACTURER_ID</code>.
     */
    public Long getManufacturerId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raadsmarine.Manufacturer.ADDRESS_LINE1</code>.
     */
    public void setAddressLine1(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raadsmarine.Manufacturer.ADDRESS_LINE1</code>.
     */
    public String getAddressLine1() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raadsmarine.Manufacturer.ADDRESS_LINE2</code>.
     */
    public void setAddressLine2(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>raadsmarine.Manufacturer.ADDRESS_LINE2</code>.
     */
    public String getAddressLine2() {
        return (String) get(2);
    }

    /**
     * Setter for <code>raadsmarine.Manufacturer.MANUFACTURER_NAME</code>.
     */
    public void setManufacturerName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>raadsmarine.Manufacturer.MANUFACTURER_NAME</code>.
     */
    public String getManufacturerName() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Manufacturer.MANUFACTURER.MANUFACTURER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Manufacturer.MANUFACTURER.ADDRESS_LINE1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Manufacturer.MANUFACTURER.ADDRESS_LINE2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Manufacturer.MANUFACTURER.MANUFACTURER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getManufacturerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAddressLine1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAddressLine2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getManufacturerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getManufacturerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAddressLine1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAddressLine2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getManufacturerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManufacturerRecord value1(Long value) {
        setManufacturerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManufacturerRecord value2(String value) {
        setAddressLine1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManufacturerRecord value3(String value) {
        setAddressLine2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManufacturerRecord value4(String value) {
        setManufacturerName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ManufacturerRecord values(Long value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ManufacturerRecord
     */
    public ManufacturerRecord() {
        super(Manufacturer.MANUFACTURER);
    }

    /**
     * Create a detached, initialised ManufacturerRecord
     */
    public ManufacturerRecord(Long manufacturerId, String addressLine1, String addressLine2, String manufacturerName) {
        super(Manufacturer.MANUFACTURER);

        set(0, manufacturerId);
        set(1, addressLine1);
        set(2, addressLine2);
        set(3, manufacturerName);
    }
}
