/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables.records;


import com.jooq.jooqDemo.jooq.domain.tables.tables.Notice;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NoticeRecord extends UpdatableRecordImpl<NoticeRecord> implements Record9<Long, String, Timestamp, String, Timestamp, String, String, String, Timestamp> {

    private static final long serialVersionUID = 546389989;

    /**
     * Setter for <code>raadsmarine.NOTICE.NOTICE_ID</code>.
     */
    public void setNoticeId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>raadsmarine.NOTICE.NOTICE_ID</code>.
     */
    public Long getNoticeId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raadsmarine.NOTICE.CREATED_BY</code>.
     */
    public void setCreatedBy(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raadsmarine.NOTICE.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raadsmarine.NOTICE.CREATED_DATE</code>.
     */
    public void setCreatedDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>raadsmarine.NOTICE.CREATED_DATE</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>raadsmarine.NOTICE.NOTICE_BODY</code>.
     */
    public void setNoticeBody(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>raadsmarine.NOTICE.NOTICE_BODY</code>.
     */
    public String getNoticeBody() {
        return (String) get(3);
    }

    /**
     * Setter for <code>raadsmarine.NOTICE.NOTICE_DATE</code>.
     */
    public void setNoticeDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>raadsmarine.NOTICE.NOTICE_DATE</code>.
     */
    public Timestamp getNoticeDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>raadsmarine.NOTICE.NOTICE_DESCRIPTION</code>.
     */
    public void setNoticeDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>raadsmarine.NOTICE.NOTICE_DESCRIPTION</code>.
     */
    public String getNoticeDescription() {
        return (String) get(5);
    }

    /**
     * Setter for <code>raadsmarine.NOTICE.NOTICE_HEADER</code>.
     */
    public void setNoticeHeader(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>raadsmarine.NOTICE.NOTICE_HEADER</code>.
     */
    public String getNoticeHeader() {
        return (String) get(6);
    }

    /**
     * Setter for <code>raadsmarine.NOTICE.UPDATED_BY</code>.
     */
    public void setUpdatedBy(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>raadsmarine.NOTICE.UPDATED_BY</code>.
     */
    public String getUpdatedBy() {
        return (String) get(7);
    }

    /**
     * Setter for <code>raadsmarine.NOTICE.UPDATED_DATE</code>.
     */
    public void setUpdatedDate(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>raadsmarine.NOTICE.UPDATED_DATE</code>.
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, Timestamp, String, Timestamp, String, String, String, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Long, String, Timestamp, String, Timestamp, String, String, String, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Notice.NOTICE.NOTICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Notice.NOTICE.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Notice.NOTICE.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Notice.NOTICE.NOTICE_BODY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Notice.NOTICE.NOTICE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Notice.NOTICE.NOTICE_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Notice.NOTICE.NOTICE_HEADER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Notice.NOTICE.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Notice.NOTICE.UPDATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getNoticeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getNoticeBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getNoticeDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getNoticeDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNoticeHeader();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getNoticeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNoticeBody();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getNoticeDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNoticeDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNoticeHeader();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeRecord value1(Long value) {
        setNoticeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeRecord value2(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeRecord value3(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeRecord value4(String value) {
        setNoticeBody(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeRecord value5(Timestamp value) {
        setNoticeDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeRecord value6(String value) {
        setNoticeDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeRecord value7(String value) {
        setNoticeHeader(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeRecord value8(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeRecord value9(Timestamp value) {
        setUpdatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NoticeRecord values(Long value1, String value2, Timestamp value3, String value4, Timestamp value5, String value6, String value7, String value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NoticeRecord
     */
    public NoticeRecord() {
        super(Notice.NOTICE);
    }

    /**
     * Create a detached, initialised NoticeRecord
     */
    public NoticeRecord(Long noticeId, String createdBy, Timestamp createdDate, String noticeBody, Timestamp noticeDate, String noticeDescription, String noticeHeader, String updatedBy, Timestamp updatedDate) {
        super(Notice.NOTICE);

        set(0, noticeId);
        set(1, createdBy);
        set(2, createdDate);
        set(3, noticeBody);
        set(4, noticeDate);
        set(5, noticeDescription);
        set(6, noticeHeader);
        set(7, updatedBy);
        set(8, updatedDate);
    }
}
