/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables.records;


import com.jooq.jooqDemo.jooq.domain.tables.tables.OauthApprovals;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OauthApprovalsRecord extends UpdatableRecordImpl<OauthApprovalsRecord> implements Record7<String, String, Timestamp, Timestamp, String, String, String> {

    private static final long serialVersionUID = -1015377127;

    /**
     * Setter for <code>raadsmarine.oauth_approvals.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>raadsmarine.oauth_approvals.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>raadsmarine.oauth_approvals.client_id</code>.
     */
    public void setClientId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raadsmarine.oauth_approvals.client_id</code>.
     */
    public String getClientId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raadsmarine.oauth_approvals.expiresAt</code>.
     */
    public void setExpiresat(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>raadsmarine.oauth_approvals.expiresAt</code>.
     */
    public Timestamp getExpiresat() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>raadsmarine.oauth_approvals.lastModifiedAt</code>.
     */
    public void setLastmodifiedat(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>raadsmarine.oauth_approvals.lastModifiedAt</code>.
     */
    public Timestamp getLastmodifiedat() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>raadsmarine.oauth_approvals.scope</code>.
     */
    public void setScope(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>raadsmarine.oauth_approvals.scope</code>.
     */
    public String getScope() {
        return (String) get(4);
    }

    /**
     * Setter for <code>raadsmarine.oauth_approvals.status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>raadsmarine.oauth_approvals.status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>raadsmarine.oauth_approvals.user_id</code>.
     */
    public void setUserId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>raadsmarine.oauth_approvals.user_id</code>.
     */
    public String getUserId() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Timestamp, Timestamp, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Timestamp, Timestamp, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return OauthApprovals.OAUTH_APPROVALS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OauthApprovals.OAUTH_APPROVALS.CLIENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return OauthApprovals.OAUTH_APPROVALS.EXPIRESAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return OauthApprovals.OAUTH_APPROVALS.LASTMODIFIEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return OauthApprovals.OAUTH_APPROVALS.SCOPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return OauthApprovals.OAUTH_APPROVALS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return OauthApprovals.OAUTH_APPROVALS.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getExpiresat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getLastmodifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getClientId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getExpiresat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getLastmodifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord value2(String value) {
        setClientId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord value3(Timestamp value) {
        setExpiresat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord value4(Timestamp value) {
        setLastmodifiedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord value5(String value) {
        setScope(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord value6(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord value7(String value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord values(String value1, String value2, Timestamp value3, Timestamp value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OauthApprovalsRecord
     */
    public OauthApprovalsRecord() {
        super(OauthApprovals.OAUTH_APPROVALS);
    }

    /**
     * Create a detached, initialised OauthApprovalsRecord
     */
    public OauthApprovalsRecord(String id, String clientId, Timestamp expiresat, Timestamp lastmodifiedat, String scope, String status, String userId) {
        super(OauthApprovals.OAUTH_APPROVALS);

        set(0, id);
        set(1, clientId);
        set(2, expiresat);
        set(3, lastmodifiedat);
        set(4, scope);
        set(5, status);
        set(6, userId);
    }
}
