/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables.records;


import com.jooq.jooqDemo.jooq.domain.tables.tables.Product;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProductRecord extends UpdatableRecordImpl<ProductRecord> implements Record6<Long, String, BigDecimal, Long, Long, Long> {

    private static final long serialVersionUID = 563570113;

    /**
     * Setter for <code>raadsmarine.Product.PRODUCT_ID</code>.
     */
    public void setProductId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>raadsmarine.Product.PRODUCT_ID</code>.
     */
    public Long getProductId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raadsmarine.Product.PRODUCT_NAME</code>.
     */
    public void setProductName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raadsmarine.Product.PRODUCT_NAME</code>.
     */
    public String getProductName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raadsmarine.Product.PRODUCT_PRICE</code>.
     */
    public void setProductPrice(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>raadsmarine.Product.PRODUCT_PRICE</code>.
     */
    public BigDecimal getProductPrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>raadsmarine.Product.category_CATEGORY_ID</code>.
     */
    public void setCategoryCategoryId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>raadsmarine.Product.category_CATEGORY_ID</code>.
     */
    public Long getCategoryCategoryId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>raadsmarine.Product.manufacturer_MANUFACTURER_ID</code>.
     */
    public void setManufacturerManufacturerId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>raadsmarine.Product.manufacturer_MANUFACTURER_ID</code>.
     */
    public Long getManufacturerManufacturerId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>raadsmarine.Product.productDetail_DETAIL_ID</code>.
     */
    public void setProductdetailDetailId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>raadsmarine.Product.productDetail_DETAIL_ID</code>.
     */
    public Long getProductdetailDetailId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, BigDecimal, Long, Long, Long> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, String, BigDecimal, Long, Long, Long> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Product.PRODUCT.PRODUCT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Product.PRODUCT.PRODUCT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return Product.PRODUCT.PRODUCT_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Product.PRODUCT.CATEGORY_CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Product.PRODUCT.MANUFACTURER_MANUFACTURER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Product.PRODUCT.PRODUCTDETAIL_DETAIL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProductName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getProductPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getCategoryCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getManufacturerManufacturerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getProductdetailDetailId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getProductId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProductName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getProductPrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getCategoryCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getManufacturerManufacturerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getProductdetailDetailId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value1(Long value) {
        setProductId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value2(String value) {
        setProductName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value3(BigDecimal value) {
        setProductPrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value4(Long value) {
        setCategoryCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value5(Long value) {
        setManufacturerManufacturerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord value6(Long value) {
        setProductdetailDetailId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProductRecord values(Long value1, String value2, BigDecimal value3, Long value4, Long value5, Long value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProductRecord
     */
    public ProductRecord() {
        super(Product.PRODUCT);
    }

    /**
     * Create a detached, initialised ProductRecord
     */
    public ProductRecord(Long productId, String productName, BigDecimal productPrice, Long categoryCategoryId, Long manufacturerManufacturerId, Long productdetailDetailId) {
        super(Product.PRODUCT);

        set(0, productId);
        set(1, productName);
        set(2, productPrice);
        set(3, categoryCategoryId);
        set(4, manufacturerManufacturerId);
        set(5, productdetailDetailId);
    }
}
