/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables.records;


import com.jooq.jooqDemo.jooq.domain.tables.tables.RoleModule;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleModuleRecord extends UpdatableRecordImpl<RoleModuleRecord> implements Record10<String, String, Timestamp, Boolean, Boolean, String, Timestamp, Boolean, String, Long> {

    private static final long serialVersionUID = 1973906390;

    /**
     * Setter for <code>raadsmarine.ROLE_MODULE.ROLE_MODULE_ID</code>.
     */
    public void setRoleModuleId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>raadsmarine.ROLE_MODULE.ROLE_MODULE_ID</code>.
     */
    public String getRoleModuleId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>raadsmarine.ROLE_MODULE.CREATED_BY</code>.
     */
    public void setCreatedBy(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raadsmarine.ROLE_MODULE.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raadsmarine.ROLE_MODULE.CREATED_DATE</code>.
     */
    public void setCreatedDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>raadsmarine.ROLE_MODULE.CREATED_DATE</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>raadsmarine.ROLE_MODULE.CAN_DELETE</code>.
     */
    public void setCanDelete(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>raadsmarine.ROLE_MODULE.CAN_DELETE</code>.
     */
    public Boolean getCanDelete() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>raadsmarine.ROLE_MODULE.CAN_UPDATE</code>.
     */
    public void setCanUpdate(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>raadsmarine.ROLE_MODULE.CAN_UPDATE</code>.
     */
    public Boolean getCanUpdate() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>raadsmarine.ROLE_MODULE.UPDATED_BY</code>.
     */
    public void setUpdatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>raadsmarine.ROLE_MODULE.UPDATED_BY</code>.
     */
    public String getUpdatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>raadsmarine.ROLE_MODULE.UPDATED_DATE</code>.
     */
    public void setUpdatedDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>raadsmarine.ROLE_MODULE.UPDATED_DATE</code>.
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>raadsmarine.ROLE_MODULE.CAN_VIEW</code>.
     */
    public void setCanView(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>raadsmarine.ROLE_MODULE.CAN_VIEW</code>.
     */
    public Boolean getCanView() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>raadsmarine.ROLE_MODULE.MODULE_ID</code>.
     */
    public void setModuleId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>raadsmarine.ROLE_MODULE.MODULE_ID</code>.
     */
    public String getModuleId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>raadsmarine.ROLE_MODULE.ROLE_ID</code>.
     */
    public void setRoleId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>raadsmarine.ROLE_MODULE.ROLE_ID</code>.
     */
    public Long getRoleId() {
        return (Long) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, Timestamp, Boolean, Boolean, String, Timestamp, Boolean, String, Long> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, Timestamp, Boolean, Boolean, String, Timestamp, Boolean, String, Long> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return RoleModule.ROLE_MODULE.ROLE_MODULE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return RoleModule.ROLE_MODULE.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return RoleModule.ROLE_MODULE.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return RoleModule.ROLE_MODULE.CAN_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return RoleModule.ROLE_MODULE.CAN_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return RoleModule.ROLE_MODULE.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return RoleModule.ROLE_MODULE.UPDATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return RoleModule.ROLE_MODULE.CAN_VIEW;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return RoleModule.ROLE_MODULE.MODULE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field10() {
        return RoleModule.ROLE_MODULE.ROLE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getRoleModuleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getCanDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component5() {
        return getCanUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getCanView();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getModuleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component10() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getRoleModuleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getCanDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getCanUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getCanView();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getModuleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value10() {
        return getRoleId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleModuleRecord value1(String value) {
        setRoleModuleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleModuleRecord value2(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleModuleRecord value3(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleModuleRecord value4(Boolean value) {
        setCanDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleModuleRecord value5(Boolean value) {
        setCanUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleModuleRecord value6(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleModuleRecord value7(Timestamp value) {
        setUpdatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleModuleRecord value8(Boolean value) {
        setCanView(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleModuleRecord value9(String value) {
        setModuleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleModuleRecord value10(Long value) {
        setRoleId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RoleModuleRecord values(String value1, String value2, Timestamp value3, Boolean value4, Boolean value5, String value6, Timestamp value7, Boolean value8, String value9, Long value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RoleModuleRecord
     */
    public RoleModuleRecord() {
        super(RoleModule.ROLE_MODULE);
    }

    /**
     * Create a detached, initialised RoleModuleRecord
     */
    public RoleModuleRecord(String roleModuleId, String createdBy, Timestamp createdDate, Boolean canDelete, Boolean canUpdate, String updatedBy, Timestamp updatedDate, Boolean canView, String moduleId, Long roleId) {
        super(RoleModule.ROLE_MODULE);

        set(0, roleModuleId);
        set(1, createdBy);
        set(2, createdDate);
        set(3, canDelete);
        set(4, canUpdate);
        set(5, updatedBy);
        set(6, updatedDate);
        set(7, canView);
        set(8, moduleId);
        set(9, roleId);
    }
}
