/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables.records;


import com.jooq.jooqDemo.jooq.domain.tables.tables.Staff;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffRecord extends UpdatableRecordImpl<StaffRecord> implements Record17<Long, String, Integer, Integer, String, String, Timestamp, Integer, Integer, Integer, String, String, String, String, Timestamp, Long, Long> {

    private static final long serialVersionUID = 1339855390;

    /**
     * Setter for <code>raadsmarine.STAFF.PERSON_ID</code>.
     */
    public void setPersonId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.PERSON_ID</code>.
     */
    public Long getPersonId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.ADDRESS</code>.
     */
    public void setAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.ADDRESS</code>.
     */
    public String getAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.AREA</code>.
     */
    public void setArea(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.AREA</code>.
     */
    public Integer getArea() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.CITY</code>.
     */
    public void setCity(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.CITY</code>.
     */
    public Integer getCity() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.COUNTRY</code>.
     */
    public void setCountry(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.COUNTRY</code>.
     */
    public String getCountry() {
        return (String) get(4);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.CREATED_BY</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.CREATED_DATE</code>.
     */
    public void setCreatedDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.CREATED_DATE</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.DISTRICT</code>.
     */
    public void setDistrict(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.DISTRICT</code>.
     */
    public Integer getDistrict() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.STATE</code>.
     */
    public void setState(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.STATE</code>.
     */
    public Integer getState() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.SUB_AREA</code>.
     */
    public void setSubArea(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.SUB_AREA</code>.
     */
    public Integer getSubArea() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.TEACHER_FIRST_NAME</code>.
     */
    public void setTeacherFirstName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.TEACHER_FIRST_NAME</code>.
     */
    public String getTeacherFirstName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.TEACHER_LAST_NAME</code>.
     */
    public void setTeacherLastName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.TEACHER_LAST_NAME</code>.
     */
    public String getTeacherLastName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.TEACHER_MIDDLE_NAME</code>.
     */
    public void setTeacherMiddleName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.TEACHER_MIDDLE_NAME</code>.
     */
    public String getTeacherMiddleName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.UPDATED_BY</code>.
     */
    public void setUpdatedBy(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.UPDATED_BY</code>.
     */
    public String getUpdatedBy() {
        return (String) get(13);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.UPDATED_DATE</code>.
     */
    public void setUpdatedDate(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.UPDATED_DATE</code>.
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.standard_STANDARD_ID</code>.
     */
    public void setStandardStandardId(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.standard_STANDARD_ID</code>.
     */
    public Long getStandardStandardId() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>raadsmarine.STAFF.user_UserId</code>.
     */
    public void setUserUserid(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>raadsmarine.STAFF.user_UserId</code>.
     */
    public Long getUserUserid() {
        return (Long) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, String, Integer, Integer, String, String, Timestamp, Integer, Integer, Integer, String, String, String, String, Timestamp, Long, Long> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, String, Integer, Integer, String, String, Timestamp, Integer, Integer, Integer, String, String, String, String, Timestamp, Long, Long> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Staff.STAFF.PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Staff.STAFF.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Staff.STAFF.AREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Staff.STAFF.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Staff.STAFF.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Staff.STAFF.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Staff.STAFF.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Staff.STAFF.DISTRICT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Staff.STAFF.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Staff.STAFF.SUB_AREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Staff.STAFF.TEACHER_FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Staff.STAFF.TEACHER_LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Staff.STAFF.TEACHER_MIDDLE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Staff.STAFF.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return Staff.STAFF.UPDATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field16() {
        return Staff.STAFF.STANDARD_STANDARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field17() {
        return Staff.STAFF.USER_USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getSubArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getTeacherFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getTeacherLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getTeacherMiddleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component15() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component16() {
        return getStandardStandardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component17() {
        return getUserUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getSubArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getTeacherFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTeacherLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getTeacherMiddleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value16() {
        return getStandardStandardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value17() {
        return getUserUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value1(Long value) {
        setPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value2(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value3(Integer value) {
        setArea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value4(Integer value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value5(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value6(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value7(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value8(Integer value) {
        setDistrict(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value9(Integer value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value10(Integer value) {
        setSubArea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value11(String value) {
        setTeacherFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value12(String value) {
        setTeacherLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value13(String value) {
        setTeacherMiddleName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value14(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value15(Timestamp value) {
        setUpdatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value16(Long value) {
        setStandardStandardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord value17(Long value) {
        setUserUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StaffRecord values(Long value1, String value2, Integer value3, Integer value4, String value5, String value6, Timestamp value7, Integer value8, Integer value9, Integer value10, String value11, String value12, String value13, String value14, Timestamp value15, Long value16, Long value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StaffRecord
     */
    public StaffRecord() {
        super(Staff.STAFF);
    }

    /**
     * Create a detached, initialised StaffRecord
     */
    public StaffRecord(Long personId, String address, Integer area, Integer city, String country, String createdBy, Timestamp createdDate, Integer district, Integer state, Integer subArea, String teacherFirstName, String teacherLastName, String teacherMiddleName, String updatedBy, Timestamp updatedDate, Long standardStandardId, Long userUserid) {
        super(Staff.STAFF);

        set(0, personId);
        set(1, address);
        set(2, area);
        set(3, city);
        set(4, country);
        set(5, createdBy);
        set(6, createdDate);
        set(7, district);
        set(8, state);
        set(9, subArea);
        set(10, teacherFirstName);
        set(11, teacherLastName);
        set(12, teacherMiddleName);
        set(13, updatedBy);
        set(14, updatedDate);
        set(15, standardStandardId);
        set(16, userUserid);
    }
}
