/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables.records;


import com.jooq.jooqDemo.jooq.domain.tables.tables.Student;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StudentRecord extends UpdatableRecordImpl<StudentRecord> implements Record21<Long, String, Long, Integer, String, String, Timestamp, Long, String, Integer, Integer, String, String, String, String, String, Long, String, Timestamp, Long, Long> {

    private static final long serialVersionUID = -257165733;

    /**
     * Setter for <code>raadsmarine.STUDENT.PERSON_ID</code>.
     */
    public void setPersonId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.PERSON_ID</code>.
     */
    public Long getPersonId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.ADDRESS</code>.
     */
    public void setAddress(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.ADDRESS</code>.
     */
    public String getAddress() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.AREA</code>.
     */
    public void setArea(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.AREA</code>.
     */
    public Long getArea() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.CITY</code>.
     */
    public void setCity(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.CITY</code>.
     */
    public Integer getCity() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.COUNTRY</code>.
     */
    public void setCountry(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.COUNTRY</code>.
     */
    public String getCountry() {
        return (String) get(4);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.CREATED_BY</code>.
     */
    public void setCreatedBy(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.CREATED_BY</code>.
     */
    public String getCreatedBy() {
        return (String) get(5);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.CREATED_DATE</code>.
     */
    public void setCreatedDate(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.CREATED_DATE</code>.
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.DISTRICT</code>.
     */
    public void setDistrict(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.DISTRICT</code>.
     */
    public Long getDistrict() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.MOBILE_NUMBER</code>.
     */
    public void setMobileNumber(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.MOBILE_NUMBER</code>.
     */
    public String getMobileNumber() {
        return (String) get(8);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.PIN</code>.
     */
    public void setPin(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.PIN</code>.
     */
    public Integer getPin() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.STATE</code>.
     */
    public void setState(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.STATE</code>.
     */
    public Integer getState() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.STUDENT_FIRST_NAME</code>.
     */
    public void setStudentFirstName(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.STUDENT_FIRST_NAME</code>.
     */
    public String getStudentFirstName() {
        return (String) get(11);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.STUDENT_LAST_NAME</code>.
     */
    public void setStudentLastName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.STUDENT_LAST_NAME</code>.
     */
    public String getStudentLastName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.STUDENT_MIDDLE_NAME</code>.
     */
    public void setStudentMiddleName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.STUDENT_MIDDLE_NAME</code>.
     */
    public String getStudentMiddleName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.STUDENT_PARENT_FIRST_NAME</code>.
     */
    public void setStudentParentFirstName(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.STUDENT_PARENT_FIRST_NAME</code>.
     */
    public String getStudentParentFirstName() {
        return (String) get(14);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.STUDENT_PARENT_LAST_NAME</code>.
     */
    public void setStudentParentLastName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.STUDENT_PARENT_LAST_NAME</code>.
     */
    public String getStudentParentLastName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.SUB_AREA</code>.
     */
    public void setSubArea(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.SUB_AREA</code>.
     */
    public Long getSubArea() {
        return (Long) get(16);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.UPDATED_BY</code>.
     */
    public void setUpdatedBy(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.UPDATED_BY</code>.
     */
    public String getUpdatedBy() {
        return (String) get(17);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.UPDATED_DATE</code>.
     */
    public void setUpdatedDate(Timestamp value) {
        set(18, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.UPDATED_DATE</code>.
     */
    public Timestamp getUpdatedDate() {
        return (Timestamp) get(18);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.standard_STANDARD_ID</code>.
     */
    public void setStandardStandardId(Long value) {
        set(19, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.standard_STANDARD_ID</code>.
     */
    public Long getStandardStandardId() {
        return (Long) get(19);
    }

    /**
     * Setter for <code>raadsmarine.STUDENT.user_UserId</code>.
     */
    public void setUserUserid(Long value) {
        set(20, value);
    }

    /**
     * Getter for <code>raadsmarine.STUDENT.user_UserId</code>.
     */
    public Long getUserUserid() {
        return (Long) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Long, String, Long, Integer, String, String, Timestamp, Long, String, Integer, Integer, String, String, String, String, String, Long, String, Timestamp, Long, Long> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row21<Long, String, Long, Integer, String, String, Timestamp, Long, String, Integer, Integer, String, String, String, String, String, Long, String, Timestamp, Long, Long> valuesRow() {
        return (Row21) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Student.STUDENT.PERSON_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Student.STUDENT.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Student.STUDENT.AREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Student.STUDENT.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Student.STUDENT.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Student.STUDENT.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Student.STUDENT.CREATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Student.STUDENT.DISTRICT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Student.STUDENT.MOBILE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return Student.STUDENT.PIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return Student.STUDENT.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Student.STUDENT.STUDENT_FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Student.STUDENT.STUDENT_LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Student.STUDENT.STUDENT_MIDDLE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Student.STUDENT.STUDENT_PARENT_FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Student.STUDENT.STUDENT_PARENT_LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field17() {
        return Student.STUDENT.SUB_AREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return Student.STUDENT.UPDATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field19() {
        return Student.STUDENT.UPDATED_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field20() {
        return Student.STUDENT.STANDARD_STANDARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field21() {
        return Student.STUDENT.USER_USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getMobileNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getPin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getStudentFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getStudentLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getStudentMiddleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getStudentParentFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getStudentParentLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component17() {
        return getSubArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component18() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component19() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component20() {
        return getStandardStandardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component21() {
        return getUserUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getPersonId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getMobileNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getPin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getStudentFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getStudentLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getStudentMiddleName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getStudentParentFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getStudentParentLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value17() {
        return getSubArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getUpdatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value19() {
        return getUpdatedDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value20() {
        return getStandardStandardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value21() {
        return getUserUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value1(Long value) {
        setPersonId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value2(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value3(Long value) {
        setArea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value4(Integer value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value5(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value6(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value7(Timestamp value) {
        setCreatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value8(Long value) {
        setDistrict(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value9(String value) {
        setMobileNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value10(Integer value) {
        setPin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value11(Integer value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value12(String value) {
        setStudentFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value13(String value) {
        setStudentLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value14(String value) {
        setStudentMiddleName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value15(String value) {
        setStudentParentFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value16(String value) {
        setStudentParentLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value17(Long value) {
        setSubArea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value18(String value) {
        setUpdatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value19(Timestamp value) {
        setUpdatedDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value20(Long value) {
        setStandardStandardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord value21(Long value) {
        setUserUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public StudentRecord values(Long value1, String value2, Long value3, Integer value4, String value5, String value6, Timestamp value7, Long value8, String value9, Integer value10, Integer value11, String value12, String value13, String value14, String value15, String value16, Long value17, String value18, Timestamp value19, Long value20, Long value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StudentRecord
     */
    public StudentRecord() {
        super(Student.STUDENT);
    }

    /**
     * Create a detached, initialised StudentRecord
     */
    public StudentRecord(Long personId, String address, Long area, Integer city, String country, String createdBy, Timestamp createdDate, Long district, String mobileNumber, Integer pin, Integer state, String studentFirstName, String studentLastName, String studentMiddleName, String studentParentFirstName, String studentParentLastName, Long subArea, String updatedBy, Timestamp updatedDate, Long standardStandardId, Long userUserid) {
        super(Student.STUDENT);

        set(0, personId);
        set(1, address);
        set(2, area);
        set(3, city);
        set(4, country);
        set(5, createdBy);
        set(6, createdDate);
        set(7, district);
        set(8, mobileNumber);
        set(9, pin);
        set(10, state);
        set(11, studentFirstName);
        set(12, studentLastName);
        set(13, studentMiddleName);
        set(14, studentParentFirstName);
        set(15, studentParentLastName);
        set(16, subArea);
        set(17, updatedBy);
        set(18, updatedDate);
        set(19, standardStandardId);
        set(20, userUserid);
    }
}
