/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables.tables.records;


import com.jooq.jooqDemo.jooq.domain.tables.tables.Userrolemapping;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserrolemappingRecord extends UpdatableRecordImpl<UserrolemappingRecord> implements Record7<Long, String, Timestamp, String, Timestamp, Long, Long> {

    private static final long serialVersionUID = -1714138102;

    /**
     * Setter for <code>raadsmarine.UserRoleMapping.UserRoleId</code>.
     */
    public void setUserroleid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>raadsmarine.UserRoleMapping.UserRoleId</code>.
     */
    public Long getUserroleid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>raadsmarine.UserRoleMapping.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>raadsmarine.UserRoleMapping.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(1);
    }

    /**
     * Setter for <code>raadsmarine.UserRoleMapping.CreatedDate</code>.
     */
    public void setCreateddate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>raadsmarine.UserRoleMapping.CreatedDate</code>.
     */
    public Timestamp getCreateddate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>raadsmarine.UserRoleMapping.UpdatedBy</code>.
     */
    public void setUpdatedby(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>raadsmarine.UserRoleMapping.UpdatedBy</code>.
     */
    public String getUpdatedby() {
        return (String) get(3);
    }

    /**
     * Setter for <code>raadsmarine.UserRoleMapping.UpdatedDate</code>.
     */
    public void setUpdateddate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>raadsmarine.UserRoleMapping.UpdatedDate</code>.
     */
    public Timestamp getUpdateddate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>raadsmarine.UserRoleMapping.role_RoleId</code>.
     */
    public void setRoleRoleid(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>raadsmarine.UserRoleMapping.role_RoleId</code>.
     */
    public Long getRoleRoleid() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>raadsmarine.UserRoleMapping.user_UserId</code>.
     */
    public void setUserUserid(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>raadsmarine.UserRoleMapping.user_UserId</code>.
     */
    public Long getUserUserid() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, Timestamp, String, Timestamp, Long, Long> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Long, String, Timestamp, String, Timestamp, Long, Long> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Userrolemapping.USERROLEMAPPING.USERROLEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Userrolemapping.USERROLEMAPPING.CREATED_BY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Userrolemapping.USERROLEMAPPING.CREATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Userrolemapping.USERROLEMAPPING.UPDATEDBY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Userrolemapping.USERROLEMAPPING.UPDATEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field6() {
        return Userrolemapping.USERROLEMAPPING.ROLE_ROLEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Userrolemapping.USERROLEMAPPING.USER_USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getUserroleid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getUpdatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component6() {
        return getRoleRoleid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getUserUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getUserroleid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getUpdatedby();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdateddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value6() {
        return getRoleRoleid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getUserUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserrolemappingRecord value1(Long value) {
        setUserroleid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserrolemappingRecord value2(String value) {
        setCreatedBy(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserrolemappingRecord value3(Timestamp value) {
        setCreateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserrolemappingRecord value4(String value) {
        setUpdatedby(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserrolemappingRecord value5(Timestamp value) {
        setUpdateddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserrolemappingRecord value6(Long value) {
        setRoleRoleid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserrolemappingRecord value7(Long value) {
        setUserUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserrolemappingRecord values(Long value1, String value2, Timestamp value3, String value4, Timestamp value5, Long value6, Long value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserrolemappingRecord
     */
    public UserrolemappingRecord() {
        super(Userrolemapping.USERROLEMAPPING);
    }

    /**
     * Create a detached, initialised UserrolemappingRecord
     */
    public UserrolemappingRecord(Long userroleid, String createdBy, Timestamp createddate, String updatedby, Timestamp updateddate, Long roleRoleid, Long userUserid) {
        super(Userrolemapping.USERROLEMAPPING);

        set(0, userroleid);
        set(1, createdBy);
        set(2, createddate);
        set(3, updatedby);
        set(4, updateddate);
        set(5, roleRoleid);
        set(6, userUserid);
    }
}
