/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables;


import com.jooq.jooqDemo.jooq.domain.tables.tables.Apple;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Audit;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Ball;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Category;
import com.jooq.jooqDemo.jooq.domain.tables.tables.ChildLookup;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Feedback;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Image;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Manufacturer;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Meeting;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Module;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Mycompanyinfo;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Notice;
import com.jooq.jooqDemo.jooq.domain.tables.tables.NoticeRole;
import com.jooq.jooqDemo.jooq.domain.tables.tables.OauthAccessToken;
import com.jooq.jooqDemo.jooq.domain.tables.tables.OauthApprovals;
import com.jooq.jooqDemo.jooq.domain.tables.tables.OauthClientDetails;
import com.jooq.jooqDemo.jooq.domain.tables.tables.OauthClientToken;
import com.jooq.jooqDemo.jooq.domain.tables.tables.OauthCode;
import com.jooq.jooqDemo.jooq.domain.tables.tables.OauthRefreshToken;
import com.jooq.jooqDemo.jooq.domain.tables.tables.ParentLookup;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Product;
import com.jooq.jooqDemo.jooq.domain.tables.tables.ProductDetails;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Productdummy;
import com.jooq.jooqDemo.jooq.domain.tables.tables.ProductdummyProduct;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Role;
import com.jooq.jooqDemo.jooq.domain.tables.tables.RoleModule;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Services;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Staff;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Standard;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Student;
import com.jooq.jooqDemo.jooq.domain.tables.tables.User;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Userrolemapping;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>raadsmarine</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index APPLE_PRIMARY = Indexes0.APPLE_PRIMARY;
    public static final Index AUDIT_PRIMARY = Indexes0.AUDIT_PRIMARY;
    public static final Index BALL_PRIMARY = Indexes0.BALL_PRIMARY;
    public static final Index CATEGORY_FK_7SCUX04NKPOUXDY2I6H8UPDIO = Indexes0.CATEGORY_FK_7SCUX04NKPOUXDY2I6H8UPDIO;
    public static final Index CATEGORY_PRIMARY = Indexes0.CATEGORY_PRIMARY;
    public static final Index CHILD_LOOKUP_FK_D84B13YB1CC24J219UVS58SRG = Indexes0.CHILD_LOOKUP_FK_D84B13YB1CC24J219UVS58SRG;
    public static final Index CHILD_LOOKUP_PRIMARY = Indexes0.CHILD_LOOKUP_PRIMARY;
    public static final Index FEEDBACK_FK_MY0AC7AYKAIP5SB6HGS37VOH = Indexes0.FEEDBACK_FK_MY0AC7AYKAIP5SB6HGS37VOH;
    public static final Index FEEDBACK_PRIMARY = Indexes0.FEEDBACK_PRIMARY;
    public static final Index IMAGE_FK_SI2J3FW2COJH0V72NT5SN0QFY = Indexes0.IMAGE_FK_SI2J3FW2COJH0V72NT5SN0QFY;
    public static final Index IMAGE_PRIMARY = Indexes0.IMAGE_PRIMARY;
    public static final Index MANUFACTURER_PRIMARY = Indexes0.MANUFACTURER_PRIMARY;
    public static final Index MEETING_FK_IRTN2CBI2KCEIHJDULKAYFG1E = Indexes0.MEETING_FK_IRTN2CBI2KCEIHJDULKAYFG1E;
    public static final Index MEETING_PRIMARY = Indexes0.MEETING_PRIMARY;
    public static final Index MODULE_PRIMARY = Indexes0.MODULE_PRIMARY;
    public static final Index MYCOMPANYINFO_PRIMARY = Indexes0.MYCOMPANYINFO_PRIMARY;
    public static final Index NOTICE_PRIMARY = Indexes0.NOTICE_PRIMARY;
    public static final Index NOTICE_ROLE_FK_T1YBVV6RRFDI74UNV22YK51S7 = Indexes0.NOTICE_ROLE_FK_T1YBVV6RRFDI74UNV22YK51S7;
    public static final Index NOTICE_ROLE_UK_3H4G8J3CTYHYUGHB26TYHJUT3 = Indexes0.NOTICE_ROLE_UK_3H4G8J3CTYHYUGHB26TYHJUT3;
    public static final Index OAUTH_ACCESS_TOKEN_PRIMARY = Indexes0.OAUTH_ACCESS_TOKEN_PRIMARY;
    public static final Index OAUTH_APPROVALS_PRIMARY = Indexes0.OAUTH_APPROVALS_PRIMARY;
    public static final Index OAUTH_CLIENT_DETAILS_PRIMARY = Indexes0.OAUTH_CLIENT_DETAILS_PRIMARY;
    public static final Index OAUTH_CLIENT_TOKEN_PRIMARY = Indexes0.OAUTH_CLIENT_TOKEN_PRIMARY;
    public static final Index OAUTH_CODE_PRIMARY = Indexes0.OAUTH_CODE_PRIMARY;
    public static final Index OAUTH_REFRESH_TOKEN_PRIMARY = Indexes0.OAUTH_REFRESH_TOKEN_PRIMARY;
    public static final Index PARENT_LOOKUP_PRIMARY = Indexes0.PARENT_LOOKUP_PRIMARY;
    public static final Index PRODUCT_FK_7YSG84NNNEBFW1AYUSFMGQQX1 = Indexes0.PRODUCT_FK_7YSG84NNNEBFW1AYUSFMGQQX1;
    public static final Index PRODUCT_FK_F40ERND8GK8N3N817A1Y0LHMU = Indexes0.PRODUCT_FK_F40ERND8GK8N3N817A1Y0LHMU;
    public static final Index PRODUCT_FK_PQBNOVWSSGSWCML7QJAMM4PT7 = Indexes0.PRODUCT_FK_PQBNOVWSSGSWCML7QJAMM4PT7;
    public static final Index PRODUCT_PRIMARY = Indexes0.PRODUCT_PRIMARY;
    public static final Index PRODUCTDUMMY_PRIMARY = Indexes0.PRODUCTDUMMY_PRIMARY;
    public static final Index PRODUCTDUMMY_PRODUCT_FK_5KHTQI5R9OKC5SHS1YGQYH3AR = Indexes0.PRODUCTDUMMY_PRODUCT_FK_5KHTQI5R9OKC5SHS1YGQYH3AR;
    public static final Index PRODUCTDUMMY_PRODUCT_FK_6A7IN2SX4D06B44VXY60W2GXR = Indexes0.PRODUCTDUMMY_PRODUCT_FK_6A7IN2SX4D06B44VXY60W2GXR;
    public static final Index PRODUCT_DETAILS_PRIMARY = Indexes0.PRODUCT_DETAILS_PRIMARY;
    public static final Index ROLE_PRIMARY = Indexes0.ROLE_PRIMARY;
    public static final Index ROLE_MODULE_FK_J12G0HSA3FDOWTKCFDOO4NV1X = Indexes0.ROLE_MODULE_FK_J12G0HSA3FDOWTKCFDOO4NV1X;
    public static final Index ROLE_MODULE_FK_JHE6FQV41HLFNX6A9WFOB641L = Indexes0.ROLE_MODULE_FK_JHE6FQV41HLFNX6A9WFOB641L;
    public static final Index ROLE_MODULE_PRIMARY = Indexes0.ROLE_MODULE_PRIMARY;
    public static final Index SERVICES_FK_4SHYWPEQG0SXKMKWKA7QLX8LU = Indexes0.SERVICES_FK_4SHYWPEQG0SXKMKWKA7QLX8LU;
    public static final Index SERVICES_PRIMARY = Indexes0.SERVICES_PRIMARY;
    public static final Index STAFF_FK_H5BCHGE5E9QNHXYI0U5CSSH41 = Indexes0.STAFF_FK_H5BCHGE5E9QNHXYI0U5CSSH41;
    public static final Index STAFF_FK_JGVGOYYD1H0UYYBELW6KMVYOT = Indexes0.STAFF_FK_JGVGOYYD1H0UYYBELW6KMVYOT;
    public static final Index STAFF_PRIMARY = Indexes0.STAFF_PRIMARY;
    public static final Index STANDARD_PRIMARY = Indexes0.STANDARD_PRIMARY;
    public static final Index STUDENT_FK_FA4G3ACW4R880IA81CCUHNLDQ = Indexes0.STUDENT_FK_FA4G3ACW4R880IA81CCUHNLDQ;
    public static final Index STUDENT_FK_RCN7L23KVL83VQV59HSRMELR1 = Indexes0.STUDENT_FK_RCN7L23KVL83VQV59HSRMELR1;
    public static final Index STUDENT_PRIMARY = Indexes0.STUDENT_PRIMARY;
    public static final Index STUDENT_UK_7W7FCHFB0GMTCFXCKR2UI6FLM = Indexes0.STUDENT_UK_7W7FCHFB0GMTCFXCKR2UI6FLM;
    public static final Index USER_PRIMARY = Indexes0.USER_PRIMARY;
    public static final Index USER_UK_GJMPLBGFROCHNTRRKGK1Y4A3T = Indexes0.USER_UK_GJMPLBGFROCHNTRRKGK1Y4A3T;
    public static final Index USER_UK_IBCFPPMACBM81HUSXF339YQ0E = Indexes0.USER_UK_IBCFPPMACBM81HUSXF339YQ0E;
    public static final Index USERROLEMAPPING_FK_MVQV8R6HVB1VQ3GWEGP4SEBBX = Indexes0.USERROLEMAPPING_FK_MVQV8R6HVB1VQ3GWEGP4SEBBX;
    public static final Index USERROLEMAPPING_FK_TFSF450QKOGDERIV1PF729S7E = Indexes0.USERROLEMAPPING_FK_TFSF450QKOGDERIV1PF729S7E;
    public static final Index USERROLEMAPPING_PRIMARY = Indexes0.USERROLEMAPPING_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index APPLE_PRIMARY = Internal.createIndex("PRIMARY", Apple.APPLE, new OrderField[] { Apple.APPLE.ID, Apple.APPLE.TENANT }, true);
        public static Index AUDIT_PRIMARY = Internal.createIndex("PRIMARY", Audit.AUDIT, new OrderField[] { Audit.AUDIT.AUDIT_ID }, true);
        public static Index BALL_PRIMARY = Internal.createIndex("PRIMARY", Ball.BALL, new OrderField[] { Ball.BALL.ID, Ball.BALL.TENANT }, true);
        public static Index CATEGORY_FK_7SCUX04NKPOUXDY2I6H8UPDIO = Internal.createIndex("FK_7scux04nkpouxdy2i6h8updio", Category.CATEGORY, new OrderField[] { Category.CATEGORY.PARENTCATEGORY_CATEGORY_ID }, false);
        public static Index CATEGORY_PRIMARY = Internal.createIndex("PRIMARY", Category.CATEGORY, new OrderField[] { Category.CATEGORY.CATEGORY_ID }, true);
        public static Index CHILD_LOOKUP_FK_D84B13YB1CC24J219UVS58SRG = Internal.createIndex("FK_d84b13yb1cc24j219uvs58srg", ChildLookup.CHILD_LOOKUP, new OrderField[] { ChildLookup.CHILD_LOOKUP.PARENTLOOKUP_PARENT_LOOKUP_ID }, false);
        public static Index CHILD_LOOKUP_PRIMARY = Internal.createIndex("PRIMARY", ChildLookup.CHILD_LOOKUP, new OrderField[] { ChildLookup.CHILD_LOOKUP.CHILD_LOOKUP_ID }, true);
        public static Index FEEDBACK_FK_MY0AC7AYKAIP5SB6HGS37VOH = Internal.createIndex("FK_my0ac7aykaip5sb6hgs37voh", Feedback.FEEDBACK, new OrderField[] { Feedback.FEEDBACK.PRODUCT_PRODUCT_ID }, false);
        public static Index FEEDBACK_PRIMARY = Internal.createIndex("PRIMARY", Feedback.FEEDBACK, new OrderField[] { Feedback.FEEDBACK.FEEDBACK_ID }, true);
        public static Index IMAGE_FK_SI2J3FW2COJH0V72NT5SN0QFY = Internal.createIndex("FK_si2j3fw2cojh0v72nt5sn0qfy", Image.IMAGE, new OrderField[] { Image.IMAGE.PRODUCT_PRODUCT_ID }, false);
        public static Index IMAGE_PRIMARY = Internal.createIndex("PRIMARY", Image.IMAGE, new OrderField[] { Image.IMAGE.IMAGE_ID }, true);
        public static Index MANUFACTURER_PRIMARY = Internal.createIndex("PRIMARY", Manufacturer.MANUFACTURER, new OrderField[] { Manufacturer.MANUFACTURER.MANUFACTURER_ID }, true);
        public static Index MEETING_FK_IRTN2CBI2KCEIHJDULKAYFG1E = Internal.createIndex("FK_irtn2cbi2kceihjdulkayfg1e", Meeting.MEETING, new OrderField[] { Meeting.MEETING.FROMUSER_USERID }, false);
        public static Index MEETING_PRIMARY = Internal.createIndex("PRIMARY", Meeting.MEETING, new OrderField[] { Meeting.MEETING.MEETING_ID }, true);
        public static Index MODULE_PRIMARY = Internal.createIndex("PRIMARY", Module.MODULE, new OrderField[] { Module.MODULE.MODULE_ID }, true);
        public static Index MYCOMPANYINFO_PRIMARY = Internal.createIndex("PRIMARY", Mycompanyinfo.MYCOMPANYINFO, new OrderField[] { Mycompanyinfo.MYCOMPANYINFO.COMPANY_ID }, true);
        public static Index NOTICE_PRIMARY = Internal.createIndex("PRIMARY", Notice.NOTICE, new OrderField[] { Notice.NOTICE.NOTICE_ID }, true);
        public static Index NOTICE_ROLE_FK_T1YBVV6RRFDI74UNV22YK51S7 = Internal.createIndex("FK_t1ybvv6rrfdi74unv22yk51s7", NoticeRole.NOTICE_ROLE, new OrderField[] { NoticeRole.NOTICE_ROLE.NOTICE_NOTICE_ID }, false);
        public static Index NOTICE_ROLE_UK_3H4G8J3CTYHYUGHB26TYHJUT3 = Internal.createIndex("UK_3h4g8j3ctyhyughb26tyhjut3", NoticeRole.NOTICE_ROLE, new OrderField[] { NoticeRole.NOTICE_ROLE.TARGETROLES_ROLEID }, true);
        public static Index OAUTH_ACCESS_TOKEN_PRIMARY = Internal.createIndex("PRIMARY", OauthAccessToken.OAUTH_ACCESS_TOKEN, new OrderField[] { OauthAccessToken.OAUTH_ACCESS_TOKEN.AUTHENTICATION_ID }, true);
        public static Index OAUTH_APPROVALS_PRIMARY = Internal.createIndex("PRIMARY", OauthApprovals.OAUTH_APPROVALS, new OrderField[] { OauthApprovals.OAUTH_APPROVALS.ID }, true);
        public static Index OAUTH_CLIENT_DETAILS_PRIMARY = Internal.createIndex("PRIMARY", OauthClientDetails.OAUTH_CLIENT_DETAILS, new OrderField[] { OauthClientDetails.OAUTH_CLIENT_DETAILS.CLIENT_ID }, true);
        public static Index OAUTH_CLIENT_TOKEN_PRIMARY = Internal.createIndex("PRIMARY", OauthClientToken.OAUTH_CLIENT_TOKEN, new OrderField[] { OauthClientToken.OAUTH_CLIENT_TOKEN.AUTHENTICATION_ID }, true);
        public static Index OAUTH_CODE_PRIMARY = Internal.createIndex("PRIMARY", OauthCode.OAUTH_CODE, new OrderField[] { OauthCode.OAUTH_CODE.ID }, true);
        public static Index OAUTH_REFRESH_TOKEN_PRIMARY = Internal.createIndex("PRIMARY", OauthRefreshToken.OAUTH_REFRESH_TOKEN, new OrderField[] { OauthRefreshToken.OAUTH_REFRESH_TOKEN.TOKEN_ID }, true);
        public static Index PARENT_LOOKUP_PRIMARY = Internal.createIndex("PRIMARY", ParentLookup.PARENT_LOOKUP, new OrderField[] { ParentLookup.PARENT_LOOKUP.PARENT_LOOKUP_ID }, true);
        public static Index PRODUCT_FK_7YSG84NNNEBFW1AYUSFMGQQX1 = Internal.createIndex("FK_7ysg84nnnebfw1ayusfmgqqx1", Product.PRODUCT, new OrderField[] { Product.PRODUCT.PRODUCTDETAIL_DETAIL_ID }, false);
        public static Index PRODUCT_FK_F40ERND8GK8N3N817A1Y0LHMU = Internal.createIndex("FK_f40ernd8gk8n3n817a1y0lhmu", Product.PRODUCT, new OrderField[] { Product.PRODUCT.MANUFACTURER_MANUFACTURER_ID }, false);
        public static Index PRODUCT_FK_PQBNOVWSSGSWCML7QJAMM4PT7 = Internal.createIndex("FK_pqbnovwssgswcml7qjamm4pt7", Product.PRODUCT, new OrderField[] { Product.PRODUCT.CATEGORY_CATEGORY_ID }, false);
        public static Index PRODUCT_PRIMARY = Internal.createIndex("PRIMARY", Product.PRODUCT, new OrderField[] { Product.PRODUCT.PRODUCT_ID }, true);
        public static Index PRODUCTDUMMY_PRIMARY = Internal.createIndex("PRIMARY", Productdummy.PRODUCTDUMMY, new OrderField[] { Productdummy.PRODUCTDUMMY.ID }, true);
        public static Index PRODUCTDUMMY_PRODUCT_FK_5KHTQI5R9OKC5SHS1YGQYH3AR = Internal.createIndex("FK_5khtqi5r9okc5shs1ygqyh3ar", ProductdummyProduct.PRODUCTDUMMY_PRODUCT, new OrderField[] { ProductdummyProduct.PRODUCTDUMMY_PRODUCT.PRODUCTDUMMY_ID }, false);
        public static Index PRODUCTDUMMY_PRODUCT_FK_6A7IN2SX4D06B44VXY60W2GXR = Internal.createIndex("FK_6a7in2sx4d06b44vxy60w2gxr", ProductdummyProduct.PRODUCTDUMMY_PRODUCT, new OrderField[] { ProductdummyProduct.PRODUCTDUMMY_PRODUCT.PRODUCTS_PRODUCT_ID }, false);
        public static Index PRODUCT_DETAILS_PRIMARY = Internal.createIndex("PRIMARY", ProductDetails.PRODUCT_DETAILS, new OrderField[] { ProductDetails.PRODUCT_DETAILS.DETAIL_ID }, true);
        public static Index ROLE_PRIMARY = Internal.createIndex("PRIMARY", Role.ROLE, new OrderField[] { Role.ROLE.ROLEID }, true);
        public static Index ROLE_MODULE_FK_J12G0HSA3FDOWTKCFDOO4NV1X = Internal.createIndex("FK_j12g0hsa3fdowtkcfdoo4nv1x", RoleModule.ROLE_MODULE, new OrderField[] { RoleModule.ROLE_MODULE.MODULE_ID }, false);
        public static Index ROLE_MODULE_FK_JHE6FQV41HLFNX6A9WFOB641L = Internal.createIndex("FK_jhe6fqv41hlfnx6a9wfob641l", RoleModule.ROLE_MODULE, new OrderField[] { RoleModule.ROLE_MODULE.ROLE_ID }, false);
        public static Index ROLE_MODULE_PRIMARY = Internal.createIndex("PRIMARY", RoleModule.ROLE_MODULE, new OrderField[] { RoleModule.ROLE_MODULE.ROLE_MODULE_ID }, true);
        public static Index SERVICES_FK_4SHYWPEQG0SXKMKWKA7QLX8LU = Internal.createIndex("FK_4shywpeqg0sxkmkwka7qlx8lu", Services.SERVICES, new OrderField[] { Services.SERVICES.PARENTSERVICE_SERVICE_ID }, false);
        public static Index SERVICES_PRIMARY = Internal.createIndex("PRIMARY", Services.SERVICES, new OrderField[] { Services.SERVICES.SERVICE_ID }, true);
        public static Index STAFF_FK_H5BCHGE5E9QNHXYI0U5CSSH41 = Internal.createIndex("FK_h5bchge5e9qnhxyi0u5cssh41", Staff.STAFF, new OrderField[] { Staff.STAFF.STANDARD_STANDARD_ID }, false);
        public static Index STAFF_FK_JGVGOYYD1H0UYYBELW6KMVYOT = Internal.createIndex("FK_jgvgoyyd1h0uyybelw6kmvyot", Staff.STAFF, new OrderField[] { Staff.STAFF.USER_USERID }, false);
        public static Index STAFF_PRIMARY = Internal.createIndex("PRIMARY", Staff.STAFF, new OrderField[] { Staff.STAFF.PERSON_ID }, true);
        public static Index STANDARD_PRIMARY = Internal.createIndex("PRIMARY", Standard.STANDARD, new OrderField[] { Standard.STANDARD.STANDARD_ID }, true);
        public static Index STUDENT_FK_FA4G3ACW4R880IA81CCUHNLDQ = Internal.createIndex("FK_fa4g3acw4r880ia81ccuhnldq", Student.STUDENT, new OrderField[] { Student.STUDENT.STANDARD_STANDARD_ID }, false);
        public static Index STUDENT_FK_RCN7L23KVL83VQV59HSRMELR1 = Internal.createIndex("FK_rcn7l23kvl83vqv59hsrmelr1", Student.STUDENT, new OrderField[] { Student.STUDENT.USER_USERID }, false);
        public static Index STUDENT_PRIMARY = Internal.createIndex("PRIMARY", Student.STUDENT, new OrderField[] { Student.STUDENT.PERSON_ID }, true);
        public static Index STUDENT_UK_7W7FCHFB0GMTCFXCKR2UI6FLM = Internal.createIndex("UK_7w7fchfb0gmtcfxckr2ui6flm", Student.STUDENT, new OrderField[] { Student.STUDENT.MOBILE_NUMBER }, true);
        public static Index USER_PRIMARY = Internal.createIndex("PRIMARY", User.USER, new OrderField[] { User.USER.USERID }, true);
        public static Index USER_UK_GJMPLBGFROCHNTRRKGK1Y4A3T = Internal.createIndex("UK_gjmplbgfrochntrrkgk1y4a3t", User.USER, new OrderField[] { User.USER.USERNAME }, true);
        public static Index USER_UK_IBCFPPMACBM81HUSXF339YQ0E = Internal.createIndex("UK_ibcfppmacbm81husxf339yq0e", User.USER, new OrderField[] { User.USER.EMAIL }, true);
        public static Index USERROLEMAPPING_FK_MVQV8R6HVB1VQ3GWEGP4SEBBX = Internal.createIndex("FK_mvqv8r6hvb1vq3gwegp4sebbx", Userrolemapping.USERROLEMAPPING, new OrderField[] { Userrolemapping.USERROLEMAPPING.ROLE_ROLEID }, false);
        public static Index USERROLEMAPPING_FK_TFSF450QKOGDERIV1PF729S7E = Internal.createIndex("FK_tfsf450qkogderiv1pf729s7e", Userrolemapping.USERROLEMAPPING, new OrderField[] { Userrolemapping.USERROLEMAPPING.USER_USERID }, false);
        public static Index USERROLEMAPPING_PRIMARY = Internal.createIndex("PRIMARY", Userrolemapping.USERROLEMAPPING, new OrderField[] { Userrolemapping.USERROLEMAPPING.USERROLEID }, true);
    }
}
