/*
 * This file is generated by jOOQ.
*/
package com.jooq.jooqDemo.jooq.domain.tables;


import com.jooq.jooqDemo.jooq.domain.tables.tables.Apple;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Audit;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Ball;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Category;
import com.jooq.jooqDemo.jooq.domain.tables.tables.ChildLookup;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Feedback;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Image;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Manufacturer;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Meeting;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Module;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Mycompanyinfo;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Notice;
import com.jooq.jooqDemo.jooq.domain.tables.tables.NoticeRole;
import com.jooq.jooqDemo.jooq.domain.tables.tables.OauthAccessToken;
import com.jooq.jooqDemo.jooq.domain.tables.tables.OauthApprovals;
import com.jooq.jooqDemo.jooq.domain.tables.tables.OauthClientDetails;
import com.jooq.jooqDemo.jooq.domain.tables.tables.OauthClientToken;
import com.jooq.jooqDemo.jooq.domain.tables.tables.OauthCode;
import com.jooq.jooqDemo.jooq.domain.tables.tables.OauthRefreshToken;
import com.jooq.jooqDemo.jooq.domain.tables.tables.ParentLookup;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Product;
import com.jooq.jooqDemo.jooq.domain.tables.tables.ProductDetails;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Productdummy;
import com.jooq.jooqDemo.jooq.domain.tables.tables.ProductdummyProduct;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Role;
import com.jooq.jooqDemo.jooq.domain.tables.tables.RoleModule;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Services;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Staff;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Standard;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Student;
import com.jooq.jooqDemo.jooq.domain.tables.tables.User;
import com.jooq.jooqDemo.jooq.domain.tables.tables.Userrolemapping;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.AppleRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.AuditRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.BallRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.CategoryRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.ChildLookupRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.FeedbackRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.ImageRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.ManufacturerRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.MeetingRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.ModuleRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.MycompanyinfoRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.NoticeRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.NoticeRoleRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.OauthAccessTokenRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.OauthApprovalsRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.OauthClientDetailsRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.OauthClientTokenRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.OauthCodeRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.OauthRefreshTokenRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.ParentLookupRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.ProductDetailsRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.ProductRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.ProductdummyProductRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.ProductdummyRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.RoleModuleRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.RoleRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.ServicesRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.StaffRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.StandardRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.StudentRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.UserRecord;
import com.jooq.jooqDemo.jooq.domain.tables.tables.records.UserrolemappingRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>raadsmarine</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AuditRecord, Long> IDENTITY_AUDIT = Identities0.IDENTITY_AUDIT;
    public static final Identity<CategoryRecord, Long> IDENTITY_CATEGORY = Identities0.IDENTITY_CATEGORY;
    public static final Identity<ChildLookupRecord, Long> IDENTITY_CHILD_LOOKUP = Identities0.IDENTITY_CHILD_LOOKUP;
    public static final Identity<FeedbackRecord, Long> IDENTITY_FEEDBACK = Identities0.IDENTITY_FEEDBACK;
    public static final Identity<ImageRecord, Long> IDENTITY_IMAGE = Identities0.IDENTITY_IMAGE;
    public static final Identity<ManufacturerRecord, Long> IDENTITY_MANUFACTURER = Identities0.IDENTITY_MANUFACTURER;
    public static final Identity<MeetingRecord, Long> IDENTITY_MEETING = Identities0.IDENTITY_MEETING;
    public static final Identity<MycompanyinfoRecord, Long> IDENTITY_MYCOMPANYINFO = Identities0.IDENTITY_MYCOMPANYINFO;
    public static final Identity<NoticeRecord, Long> IDENTITY_NOTICE = Identities0.IDENTITY_NOTICE;
    public static final Identity<ParentLookupRecord, Long> IDENTITY_PARENT_LOOKUP = Identities0.IDENTITY_PARENT_LOOKUP;
    public static final Identity<ProductRecord, Long> IDENTITY_PRODUCT = Identities0.IDENTITY_PRODUCT;
    public static final Identity<ProductDetailsRecord, Long> IDENTITY_PRODUCT_DETAILS = Identities0.IDENTITY_PRODUCT_DETAILS;
    public static final Identity<RoleRecord, Long> IDENTITY_ROLE = Identities0.IDENTITY_ROLE;
    public static final Identity<ServicesRecord, Long> IDENTITY_SERVICES = Identities0.IDENTITY_SERVICES;
    public static final Identity<StaffRecord, Long> IDENTITY_STAFF = Identities0.IDENTITY_STAFF;
    public static final Identity<StandardRecord, Long> IDENTITY_STANDARD = Identities0.IDENTITY_STANDARD;
    public static final Identity<StudentRecord, Long> IDENTITY_STUDENT = Identities0.IDENTITY_STUDENT;
    public static final Identity<UserRecord, Long> IDENTITY_USER = Identities0.IDENTITY_USER;
    public static final Identity<UserrolemappingRecord, Long> IDENTITY_USERROLEMAPPING = Identities0.IDENTITY_USERROLEMAPPING;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AppleRecord> KEY_APPLE_PRIMARY = UniqueKeys0.KEY_APPLE_PRIMARY;
    public static final UniqueKey<AuditRecord> KEY_AUDIT_PRIMARY = UniqueKeys0.KEY_AUDIT_PRIMARY;
    public static final UniqueKey<BallRecord> KEY_BALL_PRIMARY = UniqueKeys0.KEY_BALL_PRIMARY;
    public static final UniqueKey<CategoryRecord> KEY_CATEGORY_PRIMARY = UniqueKeys0.KEY_CATEGORY_PRIMARY;
    public static final UniqueKey<ChildLookupRecord> KEY_CHILD_LOOKUP_PRIMARY = UniqueKeys0.KEY_CHILD_LOOKUP_PRIMARY;
    public static final UniqueKey<FeedbackRecord> KEY_FEEDBACK_PRIMARY = UniqueKeys0.KEY_FEEDBACK_PRIMARY;
    public static final UniqueKey<ImageRecord> KEY_IMAGE_PRIMARY = UniqueKeys0.KEY_IMAGE_PRIMARY;
    public static final UniqueKey<ManufacturerRecord> KEY_MANUFACTURER_PRIMARY = UniqueKeys0.KEY_MANUFACTURER_PRIMARY;
    public static final UniqueKey<MeetingRecord> KEY_MEETING_PRIMARY = UniqueKeys0.KEY_MEETING_PRIMARY;
    public static final UniqueKey<ModuleRecord> KEY_MODULE_PRIMARY = UniqueKeys0.KEY_MODULE_PRIMARY;
    public static final UniqueKey<MycompanyinfoRecord> KEY_MYCOMPANYINFO_PRIMARY = UniqueKeys0.KEY_MYCOMPANYINFO_PRIMARY;
    public static final UniqueKey<NoticeRecord> KEY_NOTICE_PRIMARY = UniqueKeys0.KEY_NOTICE_PRIMARY;
    public static final UniqueKey<NoticeRoleRecord> KEY_NOTICE_ROLE_UK_3H4G8J3CTYHYUGHB26TYHJUT3 = UniqueKeys0.KEY_NOTICE_ROLE_UK_3H4G8J3CTYHYUGHB26TYHJUT3;
    public static final UniqueKey<OauthAccessTokenRecord> KEY_OAUTH_ACCESS_TOKEN_PRIMARY = UniqueKeys0.KEY_OAUTH_ACCESS_TOKEN_PRIMARY;
    public static final UniqueKey<OauthApprovalsRecord> KEY_OAUTH_APPROVALS_PRIMARY = UniqueKeys0.KEY_OAUTH_APPROVALS_PRIMARY;
    public static final UniqueKey<OauthClientDetailsRecord> KEY_OAUTH_CLIENT_DETAILS_PRIMARY = UniqueKeys0.KEY_OAUTH_CLIENT_DETAILS_PRIMARY;
    public static final UniqueKey<OauthClientTokenRecord> KEY_OAUTH_CLIENT_TOKEN_PRIMARY = UniqueKeys0.KEY_OAUTH_CLIENT_TOKEN_PRIMARY;
    public static final UniqueKey<OauthCodeRecord> KEY_OAUTH_CODE_PRIMARY = UniqueKeys0.KEY_OAUTH_CODE_PRIMARY;
    public static final UniqueKey<OauthRefreshTokenRecord> KEY_OAUTH_REFRESH_TOKEN_PRIMARY = UniqueKeys0.KEY_OAUTH_REFRESH_TOKEN_PRIMARY;
    public static final UniqueKey<ParentLookupRecord> KEY_PARENT_LOOKUP_PRIMARY = UniqueKeys0.KEY_PARENT_LOOKUP_PRIMARY;
    public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = UniqueKeys0.KEY_PRODUCT_PRIMARY;
    public static final UniqueKey<ProductdummyRecord> KEY_PRODUCTDUMMY_PRIMARY = UniqueKeys0.KEY_PRODUCTDUMMY_PRIMARY;
    public static final UniqueKey<ProductDetailsRecord> KEY_PRODUCT_DETAILS_PRIMARY = UniqueKeys0.KEY_PRODUCT_DETAILS_PRIMARY;
    public static final UniqueKey<RoleRecord> KEY_ROLE_PRIMARY = UniqueKeys0.KEY_ROLE_PRIMARY;
    public static final UniqueKey<RoleModuleRecord> KEY_ROLE_MODULE_PRIMARY = UniqueKeys0.KEY_ROLE_MODULE_PRIMARY;
    public static final UniqueKey<ServicesRecord> KEY_SERVICES_PRIMARY = UniqueKeys0.KEY_SERVICES_PRIMARY;
    public static final UniqueKey<StaffRecord> KEY_STAFF_PRIMARY = UniqueKeys0.KEY_STAFF_PRIMARY;
    public static final UniqueKey<StandardRecord> KEY_STANDARD_PRIMARY = UniqueKeys0.KEY_STANDARD_PRIMARY;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = UniqueKeys0.KEY_STUDENT_PRIMARY;
    public static final UniqueKey<StudentRecord> KEY_STUDENT_UK_7W7FCHFB0GMTCFXCKR2UI6FLM = UniqueKeys0.KEY_STUDENT_UK_7W7FCHFB0GMTCFXCKR2UI6FLM;
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<UserRecord> KEY_USER_UK_IBCFPPMACBM81HUSXF339YQ0E = UniqueKeys0.KEY_USER_UK_IBCFPPMACBM81HUSXF339YQ0E;
    public static final UniqueKey<UserRecord> KEY_USER_UK_GJMPLBGFROCHNTRRKGK1Y4A3T = UniqueKeys0.KEY_USER_UK_GJMPLBGFROCHNTRRKGK1Y4A3T;
    public static final UniqueKey<UserrolemappingRecord> KEY_USERROLEMAPPING_PRIMARY = UniqueKeys0.KEY_USERROLEMAPPING_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BallRecord, AppleRecord> FK_APPLE = ForeignKeys0.FK_APPLE;
    public static final ForeignKey<CategoryRecord, CategoryRecord> FK_7SCUX04NKPOUXDY2I6H8UPDIO = ForeignKeys0.FK_7SCUX04NKPOUXDY2I6H8UPDIO;
    public static final ForeignKey<ChildLookupRecord, ParentLookupRecord> FK_D84B13YB1CC24J219UVS58SRG = ForeignKeys0.FK_D84B13YB1CC24J219UVS58SRG;
    public static final ForeignKey<FeedbackRecord, ProductRecord> FK_MY0AC7AYKAIP5SB6HGS37VOH = ForeignKeys0.FK_MY0AC7AYKAIP5SB6HGS37VOH;
    public static final ForeignKey<ImageRecord, ProductRecord> FK_SI2J3FW2COJH0V72NT5SN0QFY = ForeignKeys0.FK_SI2J3FW2COJH0V72NT5SN0QFY;
    public static final ForeignKey<MeetingRecord, UserRecord> FK_IRTN2CBI2KCEIHJDULKAYFG1E = ForeignKeys0.FK_IRTN2CBI2KCEIHJDULKAYFG1E;
    public static final ForeignKey<NoticeRoleRecord, NoticeRecord> FK_T1YBVV6RRFDI74UNV22YK51S7 = ForeignKeys0.FK_T1YBVV6RRFDI74UNV22YK51S7;
    public static final ForeignKey<NoticeRoleRecord, RoleRecord> FK_3H4G8J3CTYHYUGHB26TYHJUT3 = ForeignKeys0.FK_3H4G8J3CTYHYUGHB26TYHJUT3;
    public static final ForeignKey<ProductRecord, CategoryRecord> FK_PQBNOVWSSGSWCML7QJAMM4PT7 = ForeignKeys0.FK_PQBNOVWSSGSWCML7QJAMM4PT7;
    public static final ForeignKey<ProductRecord, ManufacturerRecord> FK_F40ERND8GK8N3N817A1Y0LHMU = ForeignKeys0.FK_F40ERND8GK8N3N817A1Y0LHMU;
    public static final ForeignKey<ProductRecord, ProductDetailsRecord> FK_7YSG84NNNEBFW1AYUSFMGQQX1 = ForeignKeys0.FK_7YSG84NNNEBFW1AYUSFMGQQX1;
    public static final ForeignKey<ProductdummyProductRecord, ProductdummyRecord> FK_5KHTQI5R9OKC5SHS1YGQYH3AR = ForeignKeys0.FK_5KHTQI5R9OKC5SHS1YGQYH3AR;
    public static final ForeignKey<ProductdummyProductRecord, ProductRecord> FK_6A7IN2SX4D06B44VXY60W2GXR = ForeignKeys0.FK_6A7IN2SX4D06B44VXY60W2GXR;
    public static final ForeignKey<RoleModuleRecord, ModuleRecord> FK_J12G0HSA3FDOWTKCFDOO4NV1X = ForeignKeys0.FK_J12G0HSA3FDOWTKCFDOO4NV1X;
    public static final ForeignKey<RoleModuleRecord, RoleRecord> FK_JHE6FQV41HLFNX6A9WFOB641L = ForeignKeys0.FK_JHE6FQV41HLFNX6A9WFOB641L;
    public static final ForeignKey<ServicesRecord, ServicesRecord> FK_4SHYWPEQG0SXKMKWKA7QLX8LU = ForeignKeys0.FK_4SHYWPEQG0SXKMKWKA7QLX8LU;
    public static final ForeignKey<StaffRecord, StandardRecord> FK_H5BCHGE5E9QNHXYI0U5CSSH41 = ForeignKeys0.FK_H5BCHGE5E9QNHXYI0U5CSSH41;
    public static final ForeignKey<StaffRecord, UserRecord> FK_JGVGOYYD1H0UYYBELW6KMVYOT = ForeignKeys0.FK_JGVGOYYD1H0UYYBELW6KMVYOT;
    public static final ForeignKey<StudentRecord, StandardRecord> FK_FA4G3ACW4R880IA81CCUHNLDQ = ForeignKeys0.FK_FA4G3ACW4R880IA81CCUHNLDQ;
    public static final ForeignKey<StudentRecord, UserRecord> FK_RCN7L23KVL83VQV59HSRMELR1 = ForeignKeys0.FK_RCN7L23KVL83VQV59HSRMELR1;
    public static final ForeignKey<UserrolemappingRecord, RoleRecord> FK_MVQV8R6HVB1VQ3GWEGP4SEBBX = ForeignKeys0.FK_MVQV8R6HVB1VQ3GWEGP4SEBBX;
    public static final ForeignKey<UserrolemappingRecord, UserRecord> FK_TFSF450QKOGDERIV1PF729S7E = ForeignKeys0.FK_TFSF450QKOGDERIV1PF729S7E;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<AuditRecord, Long> IDENTITY_AUDIT = Internal.createIdentity(Audit.AUDIT, Audit.AUDIT.AUDIT_ID);
        public static Identity<CategoryRecord, Long> IDENTITY_CATEGORY = Internal.createIdentity(Category.CATEGORY, Category.CATEGORY.CATEGORY_ID);
        public static Identity<ChildLookupRecord, Long> IDENTITY_CHILD_LOOKUP = Internal.createIdentity(ChildLookup.CHILD_LOOKUP, ChildLookup.CHILD_LOOKUP.CHILD_LOOKUP_ID);
        public static Identity<FeedbackRecord, Long> IDENTITY_FEEDBACK = Internal.createIdentity(Feedback.FEEDBACK, Feedback.FEEDBACK.FEEDBACK_ID);
        public static Identity<ImageRecord, Long> IDENTITY_IMAGE = Internal.createIdentity(Image.IMAGE, Image.IMAGE.IMAGE_ID);
        public static Identity<ManufacturerRecord, Long> IDENTITY_MANUFACTURER = Internal.createIdentity(Manufacturer.MANUFACTURER, Manufacturer.MANUFACTURER.MANUFACTURER_ID);
        public static Identity<MeetingRecord, Long> IDENTITY_MEETING = Internal.createIdentity(Meeting.MEETING, Meeting.MEETING.MEETING_ID);
        public static Identity<MycompanyinfoRecord, Long> IDENTITY_MYCOMPANYINFO = Internal.createIdentity(Mycompanyinfo.MYCOMPANYINFO, Mycompanyinfo.MYCOMPANYINFO.COMPANY_ID);
        public static Identity<NoticeRecord, Long> IDENTITY_NOTICE = Internal.createIdentity(Notice.NOTICE, Notice.NOTICE.NOTICE_ID);
        public static Identity<ParentLookupRecord, Long> IDENTITY_PARENT_LOOKUP = Internal.createIdentity(ParentLookup.PARENT_LOOKUP, ParentLookup.PARENT_LOOKUP.PARENT_LOOKUP_ID);
        public static Identity<ProductRecord, Long> IDENTITY_PRODUCT = Internal.createIdentity(Product.PRODUCT, Product.PRODUCT.PRODUCT_ID);
        public static Identity<ProductDetailsRecord, Long> IDENTITY_PRODUCT_DETAILS = Internal.createIdentity(ProductDetails.PRODUCT_DETAILS, ProductDetails.PRODUCT_DETAILS.DETAIL_ID);
        public static Identity<RoleRecord, Long> IDENTITY_ROLE = Internal.createIdentity(Role.ROLE, Role.ROLE.ROLEID);
        public static Identity<ServicesRecord, Long> IDENTITY_SERVICES = Internal.createIdentity(Services.SERVICES, Services.SERVICES.SERVICE_ID);
        public static Identity<StaffRecord, Long> IDENTITY_STAFF = Internal.createIdentity(Staff.STAFF, Staff.STAFF.PERSON_ID);
        public static Identity<StandardRecord, Long> IDENTITY_STANDARD = Internal.createIdentity(Standard.STANDARD, Standard.STANDARD.STANDARD_ID);
        public static Identity<StudentRecord, Long> IDENTITY_STUDENT = Internal.createIdentity(Student.STUDENT, Student.STUDENT.PERSON_ID);
        public static Identity<UserRecord, Long> IDENTITY_USER = Internal.createIdentity(User.USER, User.USER.USERID);
        public static Identity<UserrolemappingRecord, Long> IDENTITY_USERROLEMAPPING = Internal.createIdentity(Userrolemapping.USERROLEMAPPING, Userrolemapping.USERROLEMAPPING.USERROLEID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<AppleRecord> KEY_APPLE_PRIMARY = Internal.createUniqueKey(Apple.APPLE, "KEY_apple_PRIMARY", Apple.APPLE.ID, Apple.APPLE.TENANT);
        public static final UniqueKey<AuditRecord> KEY_AUDIT_PRIMARY = Internal.createUniqueKey(Audit.AUDIT, "KEY_Audit_PRIMARY", Audit.AUDIT.AUDIT_ID);
        public static final UniqueKey<BallRecord> KEY_BALL_PRIMARY = Internal.createUniqueKey(Ball.BALL, "KEY_ball_PRIMARY", Ball.BALL.ID, Ball.BALL.TENANT);
        public static final UniqueKey<CategoryRecord> KEY_CATEGORY_PRIMARY = Internal.createUniqueKey(Category.CATEGORY, "KEY_Category_PRIMARY", Category.CATEGORY.CATEGORY_ID);
        public static final UniqueKey<ChildLookupRecord> KEY_CHILD_LOOKUP_PRIMARY = Internal.createUniqueKey(ChildLookup.CHILD_LOOKUP, "KEY_CHILD_LOOKUP_PRIMARY", ChildLookup.CHILD_LOOKUP.CHILD_LOOKUP_ID);
        public static final UniqueKey<FeedbackRecord> KEY_FEEDBACK_PRIMARY = Internal.createUniqueKey(Feedback.FEEDBACK, "KEY_Feedback_PRIMARY", Feedback.FEEDBACK.FEEDBACK_ID);
        public static final UniqueKey<ImageRecord> KEY_IMAGE_PRIMARY = Internal.createUniqueKey(Image.IMAGE, "KEY_Image_PRIMARY", Image.IMAGE.IMAGE_ID);
        public static final UniqueKey<ManufacturerRecord> KEY_MANUFACTURER_PRIMARY = Internal.createUniqueKey(Manufacturer.MANUFACTURER, "KEY_Manufacturer_PRIMARY", Manufacturer.MANUFACTURER.MANUFACTURER_ID);
        public static final UniqueKey<MeetingRecord> KEY_MEETING_PRIMARY = Internal.createUniqueKey(Meeting.MEETING, "KEY_MEETING_PRIMARY", Meeting.MEETING.MEETING_ID);
        public static final UniqueKey<ModuleRecord> KEY_MODULE_PRIMARY = Internal.createUniqueKey(Module.MODULE, "KEY_MODULE_PRIMARY", Module.MODULE.MODULE_ID);
        public static final UniqueKey<MycompanyinfoRecord> KEY_MYCOMPANYINFO_PRIMARY = Internal.createUniqueKey(Mycompanyinfo.MYCOMPANYINFO, "KEY_MyCompanyInfo_PRIMARY", Mycompanyinfo.MYCOMPANYINFO.COMPANY_ID);
        public static final UniqueKey<NoticeRecord> KEY_NOTICE_PRIMARY = Internal.createUniqueKey(Notice.NOTICE, "KEY_NOTICE_PRIMARY", Notice.NOTICE.NOTICE_ID);
        public static final UniqueKey<NoticeRoleRecord> KEY_NOTICE_ROLE_UK_3H4G8J3CTYHYUGHB26TYHJUT3 = Internal.createUniqueKey(NoticeRole.NOTICE_ROLE, "KEY_NOTICE_Role_UK_3h4g8j3ctyhyughb26tyhjut3", NoticeRole.NOTICE_ROLE.TARGETROLES_ROLEID);
        public static final UniqueKey<OauthAccessTokenRecord> KEY_OAUTH_ACCESS_TOKEN_PRIMARY = Internal.createUniqueKey(OauthAccessToken.OAUTH_ACCESS_TOKEN, "KEY_oauth_access_token_PRIMARY", OauthAccessToken.OAUTH_ACCESS_TOKEN.AUTHENTICATION_ID);
        public static final UniqueKey<OauthApprovalsRecord> KEY_OAUTH_APPROVALS_PRIMARY = Internal.createUniqueKey(OauthApprovals.OAUTH_APPROVALS, "KEY_oauth_approvals_PRIMARY", OauthApprovals.OAUTH_APPROVALS.ID);
        public static final UniqueKey<OauthClientDetailsRecord> KEY_OAUTH_CLIENT_DETAILS_PRIMARY = Internal.createUniqueKey(OauthClientDetails.OAUTH_CLIENT_DETAILS, "KEY_oauth_client_details_PRIMARY", OauthClientDetails.OAUTH_CLIENT_DETAILS.CLIENT_ID);
        public static final UniqueKey<OauthClientTokenRecord> KEY_OAUTH_CLIENT_TOKEN_PRIMARY = Internal.createUniqueKey(OauthClientToken.OAUTH_CLIENT_TOKEN, "KEY_oauth_client_token_PRIMARY", OauthClientToken.OAUTH_CLIENT_TOKEN.AUTHENTICATION_ID);
        public static final UniqueKey<OauthCodeRecord> KEY_OAUTH_CODE_PRIMARY = Internal.createUniqueKey(OauthCode.OAUTH_CODE, "KEY_oauth_code_PRIMARY", OauthCode.OAUTH_CODE.ID);
        public static final UniqueKey<OauthRefreshTokenRecord> KEY_OAUTH_REFRESH_TOKEN_PRIMARY = Internal.createUniqueKey(OauthRefreshToken.OAUTH_REFRESH_TOKEN, "KEY_oauth_refresh_token_PRIMARY", OauthRefreshToken.OAUTH_REFRESH_TOKEN.TOKEN_ID);
        public static final UniqueKey<ParentLookupRecord> KEY_PARENT_LOOKUP_PRIMARY = Internal.createUniqueKey(ParentLookup.PARENT_LOOKUP, "KEY_PARENT_LOOKUP_PRIMARY", ParentLookup.PARENT_LOOKUP.PARENT_LOOKUP_ID);
        public static final UniqueKey<ProductRecord> KEY_PRODUCT_PRIMARY = Internal.createUniqueKey(Product.PRODUCT, "KEY_Product_PRIMARY", Product.PRODUCT.PRODUCT_ID);
        public static final UniqueKey<ProductdummyRecord> KEY_PRODUCTDUMMY_PRIMARY = Internal.createUniqueKey(Productdummy.PRODUCTDUMMY, "KEY_ProductDummy_PRIMARY", Productdummy.PRODUCTDUMMY.ID);
        public static final UniqueKey<ProductDetailsRecord> KEY_PRODUCT_DETAILS_PRIMARY = Internal.createUniqueKey(ProductDetails.PRODUCT_DETAILS, "KEY_PRODUCT_DETAILS_PRIMARY", ProductDetails.PRODUCT_DETAILS.DETAIL_ID);
        public static final UniqueKey<RoleRecord> KEY_ROLE_PRIMARY = Internal.createUniqueKey(Role.ROLE, "KEY_Role_PRIMARY", Role.ROLE.ROLEID);
        public static final UniqueKey<RoleModuleRecord> KEY_ROLE_MODULE_PRIMARY = Internal.createUniqueKey(RoleModule.ROLE_MODULE, "KEY_ROLE_MODULE_PRIMARY", RoleModule.ROLE_MODULE.ROLE_MODULE_ID);
        public static final UniqueKey<ServicesRecord> KEY_SERVICES_PRIMARY = Internal.createUniqueKey(Services.SERVICES, "KEY_Services_PRIMARY", Services.SERVICES.SERVICE_ID);
        public static final UniqueKey<StaffRecord> KEY_STAFF_PRIMARY = Internal.createUniqueKey(Staff.STAFF, "KEY_STAFF_PRIMARY", Staff.STAFF.PERSON_ID);
        public static final UniqueKey<StandardRecord> KEY_STANDARD_PRIMARY = Internal.createUniqueKey(Standard.STANDARD, "KEY_STANDARD_PRIMARY", Standard.STANDARD.STANDARD_ID);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_PRIMARY = Internal.createUniqueKey(Student.STUDENT, "KEY_STUDENT_PRIMARY", Student.STUDENT.PERSON_ID);
        public static final UniqueKey<StudentRecord> KEY_STUDENT_UK_7W7FCHFB0GMTCFXCKR2UI6FLM = Internal.createUniqueKey(Student.STUDENT, "KEY_STUDENT_UK_7w7fchfb0gmtcfxckr2ui6flm", Student.STUDENT.MOBILE_NUMBER);
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.USERID);
        public static final UniqueKey<UserRecord> KEY_USER_UK_IBCFPPMACBM81HUSXF339YQ0E = Internal.createUniqueKey(User.USER, "KEY_user_UK_ibcfppmacbm81husxf339yq0e", User.USER.EMAIL);
        public static final UniqueKey<UserRecord> KEY_USER_UK_GJMPLBGFROCHNTRRKGK1Y4A3T = Internal.createUniqueKey(User.USER, "KEY_user_UK_gjmplbgfrochntrrkgk1y4a3t", User.USER.USERNAME);
        public static final UniqueKey<UserrolemappingRecord> KEY_USERROLEMAPPING_PRIMARY = Internal.createUniqueKey(Userrolemapping.USERROLEMAPPING, "KEY_UserRoleMapping_PRIMARY", Userrolemapping.USERROLEMAPPING.USERROLEID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<BallRecord, AppleRecord> FK_APPLE = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_APPLE_PRIMARY, Ball.BALL, "fk_apple", Ball.BALL.ID, Ball.BALL.TENANT);
        public static final ForeignKey<CategoryRecord, CategoryRecord> FK_7SCUX04NKPOUXDY2I6H8UPDIO = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_CATEGORY_PRIMARY, Category.CATEGORY, "FK_7scux04nkpouxdy2i6h8updio", Category.CATEGORY.PARENTCATEGORY_CATEGORY_ID);
        public static final ForeignKey<ChildLookupRecord, ParentLookupRecord> FK_D84B13YB1CC24J219UVS58SRG = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_PARENT_LOOKUP_PRIMARY, ChildLookup.CHILD_LOOKUP, "FK_d84b13yb1cc24j219uvs58srg", ChildLookup.CHILD_LOOKUP.PARENTLOOKUP_PARENT_LOOKUP_ID);
        public static final ForeignKey<FeedbackRecord, ProductRecord> FK_MY0AC7AYKAIP5SB6HGS37VOH = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_PRODUCT_PRIMARY, Feedback.FEEDBACK, "FK_my0ac7aykaip5sb6hgs37voh", Feedback.FEEDBACK.PRODUCT_PRODUCT_ID);
        public static final ForeignKey<ImageRecord, ProductRecord> FK_SI2J3FW2COJH0V72NT5SN0QFY = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_PRODUCT_PRIMARY, Image.IMAGE, "FK_si2j3fw2cojh0v72nt5sn0qfy", Image.IMAGE.PRODUCT_PRODUCT_ID);
        public static final ForeignKey<MeetingRecord, UserRecord> FK_IRTN2CBI2KCEIHJDULKAYFG1E = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_USER_PRIMARY, Meeting.MEETING, "FK_irtn2cbi2kceihjdulkayfg1e", Meeting.MEETING.FROMUSER_USERID);
        public static final ForeignKey<NoticeRoleRecord, NoticeRecord> FK_T1YBVV6RRFDI74UNV22YK51S7 = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_NOTICE_PRIMARY, NoticeRole.NOTICE_ROLE, "FK_t1ybvv6rrfdi74unv22yk51s7", NoticeRole.NOTICE_ROLE.NOTICE_NOTICE_ID);
        public static final ForeignKey<NoticeRoleRecord, RoleRecord> FK_3H4G8J3CTYHYUGHB26TYHJUT3 = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_ROLE_PRIMARY, NoticeRole.NOTICE_ROLE, "FK_3h4g8j3ctyhyughb26tyhjut3", NoticeRole.NOTICE_ROLE.TARGETROLES_ROLEID);
        public static final ForeignKey<ProductRecord, CategoryRecord> FK_PQBNOVWSSGSWCML7QJAMM4PT7 = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_CATEGORY_PRIMARY, Product.PRODUCT, "FK_pqbnovwssgswcml7qjamm4pt7", Product.PRODUCT.CATEGORY_CATEGORY_ID);
        public static final ForeignKey<ProductRecord, ManufacturerRecord> FK_F40ERND8GK8N3N817A1Y0LHMU = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_MANUFACTURER_PRIMARY, Product.PRODUCT, "FK_f40ernd8gk8n3n817a1y0lhmu", Product.PRODUCT.MANUFACTURER_MANUFACTURER_ID);
        public static final ForeignKey<ProductRecord, ProductDetailsRecord> FK_7YSG84NNNEBFW1AYUSFMGQQX1 = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_PRODUCT_DETAILS_PRIMARY, Product.PRODUCT, "FK_7ysg84nnnebfw1ayusfmgqqx1", Product.PRODUCT.PRODUCTDETAIL_DETAIL_ID);
        public static final ForeignKey<ProductdummyProductRecord, ProductdummyRecord> FK_5KHTQI5R9OKC5SHS1YGQYH3AR = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_PRODUCTDUMMY_PRIMARY, ProductdummyProduct.PRODUCTDUMMY_PRODUCT, "FK_5khtqi5r9okc5shs1ygqyh3ar", ProductdummyProduct.PRODUCTDUMMY_PRODUCT.PRODUCTDUMMY_ID);
        public static final ForeignKey<ProductdummyProductRecord, ProductRecord> FK_6A7IN2SX4D06B44VXY60W2GXR = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_PRODUCT_PRIMARY, ProductdummyProduct.PRODUCTDUMMY_PRODUCT, "FK_6a7in2sx4d06b44vxy60w2gxr", ProductdummyProduct.PRODUCTDUMMY_PRODUCT.PRODUCTS_PRODUCT_ID);
        public static final ForeignKey<RoleModuleRecord, ModuleRecord> FK_J12G0HSA3FDOWTKCFDOO4NV1X = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_MODULE_PRIMARY, RoleModule.ROLE_MODULE, "FK_j12g0hsa3fdowtkcfdoo4nv1x", RoleModule.ROLE_MODULE.MODULE_ID);
        public static final ForeignKey<RoleModuleRecord, RoleRecord> FK_JHE6FQV41HLFNX6A9WFOB641L = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_ROLE_PRIMARY, RoleModule.ROLE_MODULE, "FK_jhe6fqv41hlfnx6a9wfob641l", RoleModule.ROLE_MODULE.ROLE_ID);
        public static final ForeignKey<ServicesRecord, ServicesRecord> FK_4SHYWPEQG0SXKMKWKA7QLX8LU = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_SERVICES_PRIMARY, Services.SERVICES, "FK_4shywpeqg0sxkmkwka7qlx8lu", Services.SERVICES.PARENTSERVICE_SERVICE_ID);
        public static final ForeignKey<StaffRecord, StandardRecord> FK_H5BCHGE5E9QNHXYI0U5CSSH41 = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_STANDARD_PRIMARY, Staff.STAFF, "FK_h5bchge5e9qnhxyi0u5cssh41", Staff.STAFF.STANDARD_STANDARD_ID);
        public static final ForeignKey<StaffRecord, UserRecord> FK_JGVGOYYD1H0UYYBELW6KMVYOT = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_USER_PRIMARY, Staff.STAFF, "FK_jgvgoyyd1h0uyybelw6kmvyot", Staff.STAFF.USER_USERID);
        public static final ForeignKey<StudentRecord, StandardRecord> FK_FA4G3ACW4R880IA81CCUHNLDQ = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_STANDARD_PRIMARY, Student.STUDENT, "FK_fa4g3acw4r880ia81ccuhnldq", Student.STUDENT.STANDARD_STANDARD_ID);
        public static final ForeignKey<StudentRecord, UserRecord> FK_RCN7L23KVL83VQV59HSRMELR1 = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_USER_PRIMARY, Student.STUDENT, "FK_rcn7l23kvl83vqv59hsrmelr1", Student.STUDENT.USER_USERID);
        public static final ForeignKey<UserrolemappingRecord, RoleRecord> FK_MVQV8R6HVB1VQ3GWEGP4SEBBX = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_ROLE_PRIMARY, Userrolemapping.USERROLEMAPPING, "FK_mvqv8r6hvb1vq3gwegp4sebbx", Userrolemapping.USERROLEMAPPING.ROLE_ROLEID);
        public static final ForeignKey<UserrolemappingRecord, UserRecord> FK_TFSF450QKOGDERIV1PF729S7E = Internal.createForeignKey(com.jooq.jooqDemo.jooq.domain.tables.Keys.KEY_USER_PRIMARY, Userrolemapping.USERROLEMAPPING, "FK_tfsf450qkogderiv1pf729s7e", Userrolemapping.USERROLEMAPPING.USER_USERID);
    }
}
